### ISSUE TITLE
How do I host glTF files from Amazon S3 and use them with <model-viewer>?

### ISSUE THREAD

**Issue by IvanNov7** [google/model-viewer#1015]
Hello every one!
Trying to run the script with model from amazon s3 but cant load model.
Maybe anyone could tell me where is the problem and what i am doing wrong ?
Here is my example: 
```
<script type="module" src="https://unpkg.com/@google/model-viewer/dist/model-viewer.js"></script>
<script nomodule src="https://unpkg.com/@google/model-viewer/dist/model-viewer-legacy.js"></script>
<model-viewer src="https://in3dreal.s3.eu-central-1.amazonaws.com/scene.glb" auto-rotate camera-controls></model-viewer>
```

**Comment by cdata** [comment]
Hey @IvanNov7 it looks like you're still not sending CORS headers in the response. Here is a help article I found on Google that describes how to enable CORS for an Amazon S3 bucket: https://docs.aws.amazon.com/AmazonS3/latest/dev/cors.html#how-do-i-enable-cors

I'm not an AWS expert, so that's the best information I can offer.

Note that you will need to enable CORS in the server that hosts your models *if and only if* that server is different from the one that hosts the `<model-viewer>` HTML. If you serve them from the same origin (that is, same protocol, domain name and port), then CORS should not be required.
