### ISSUE TITLE
Files that should be identical have different behaviour in SceneViewer

### ISSUE THREAD

**Issue by hybridherbst** [google/model-viewer#1026]
### Description

This seems to be a SceneViewer bug or something is broken with the files, but I can't figure it out.
Two files that are identical in model-viewer - one is working in SceneViewer and one is not. Both pass GLB Validation (with some UV warnings).

To reproduce: try opening the files in SceneViewer. Second one works, first one says "There's a problem with the file" and does not open.

Is there a tool to validate GLTF .bin data? 

#### Live Demo
https://honeysuckle-caravanz.glitch.me/

### Browser Affected

- [X] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Helios
- [ ] IE
- [ ] Safari

### OS

- [X] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

**Comment by cdata** [comment]
@soraryu thanks for reporting this. Have you also tried dumping the files into https://vr.google.com/scene-viewer-preview?

cc @tpsiaki

**Comment by soraryu** [comment]
Ah yes, forgot to mention that - they work in every viewer that I tried, including scene-viewer-preview. Only actual on-device SceneViewer breaks.

**Comment by cdata** [comment]
And no warning messages or errors reported by the Scene Viewer previewer?

**Comment by soraryu** [comment]
Just some information about unused UVs. Both files have exactly the same info and both 0 warnings/0 errors.
![Screenshot_2020-02-18-23-01-11-852_com android chrome](https://user-images.githubusercontent.com/2693840/74781869-a97de080-52a2-11ea-9408-1dff51a0f29a.jpg)

Tested on:
Pixel 4
Xiaomi Mi 9
Samsung S10
Samsung S9

**Comment by soraryu** [comment]
I'd like to bump this as the issue seems to be worse than we initially thought.

Nearly every animated file we tried breaks in Scene Viewer, no matter whether exported from Blender, 3D Viewer, Sketchfab, Unity. I attached some examples of files that play and validate everywhere but break in SceneViewer. Sometimes SceneViewer even just downright crashes, we also had cases where Android Chrome simply closes without any error message when trying to enter Scene Viewer on an animated file.


[Train-BrokenSceneViewer.zip](https://github.com/google/model-viewer/files/4252016/Train-BrokenSceneViewer.zip)

@tpsiaki I guess?

**Comment by soraryu** [comment]
I wish I would not have had to spend so much time on this but we have a deadline approaching and this weird bug was driving me crazy.

**Turns out that the bug is SceneViewer ignoring the spec:**
https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/schema/animation.sampler.schema.json defines that the default for animation sampling is "LINEAR". A lot of exporters thus explicitly don't export LINEAR to save a couple bytes:
![200225-231510-devenv](https://user-images.githubusercontent.com/2693840/75293430-700b1f00-5826-11ea-89d0-354bc82cf4b6.png)
(somewhere deep in a GLTF serializer)

Explicitly specifying LINEAR fixes the "this object has an issue" message.

Minimal repro object, 4KB cube with a couple keyframes, only change is explicitly specyifing LINEAR sampler for pos/rot keys for this:
https://glitch.com/edit/#!/elemental-deeply-meat

**Comment by cdata** [comment]
@soraryu sorry for all of the trouble. I pinged @tpsiaki to share your report today and he is aware of it. I'll let you know if he gets back to me. Thanks for the deep investigative work 🙇‍♂️

**Comment by tpsiaki** [comment]
Thanks for the report and detailed investigation.  We'll work on a fix for this in Scene Viewer.

**Comment by tpsiaki** [comment]
@soraryu - we have fixed these issues (no default interpolation, and short animations not loading) internally.  The fix will be rolling out in the next version of the Google app, which should be available around the end of next week.
