### ISSUE TITLE
Feature request: Add support for additional properties to enable Apple Pay Button or a Custom Action in AR Quick Look mode

### ISSUE THREAD

**Issue by rmhall** [google/model-viewer#1030]
Would be very nice to see support added for additional properties in the model-viewer markup to allow easily passing in the additional properties/params needed to enable an Apple Pay Button or a Custom Action in AR Quick Look mode. 

Reference documentation here: https://developer.apple.com/documentation/arkit/adding_an_apple_pay_button_or_a_custom_action_in_ar_quick_look

I will take a pass at editing: packages/model-viewer/src/features/ar.ts
https://github.com/google/model-viewer/blob/master/packages/model-viewer/src/features/ar.ts

Off the top of my head, it might just some need a few quick edits to the function "openIOSARQuickLook" in that file, and maybe require adding in the ability to pass in a reference to a custom listener to bind to, in order to support the Custom Action as well...  If I have some time tomorrow and get it working, will submit a PR.

**Comment by rmhall** [comment]
Quick follow up: Well part of that was easy to do without any modifications - simply pass in the required hash in the existing ios-src property like as follows:

ios-src="my_model.usdz#applePayButtonType=buy&checkoutTitle=BuyMyThingamabob&checkoutSubtitle=VeryCoolEnticingCallToAction&price=$300"

That will get you an Apple Pay "BUY" button with the title, subtitle and price displayed as noted in the documentation.

While the markup is not as readable as it could be if we broke down those name/value pairs into additional easy to read/edit properties for model-viewer, but it works fine to get your Apple Pay banner/prompt going. 

However, because of the way the openIOSARQuickLook function simply creates a new anchor tag in the dom with the ios-src url and required img tag to go to Quick Look mode - but does not assign a reference or ID, this will need to be modified to accept an id to assign it and allow the "message" listener to bind to it, if you want to be able to actually respond to tapping on the Apple Pay or custom banner as documented...

**Comment by cdata** [comment]
@rmhall great find! Thanks for doing this investigation and for the thoughtful feedback. Some of my own thoughts follow:

> While the markup is not as readable as it could be if we broke down those name/value pairs into additional easy to read/edit properties for model-viewer, but it works fine to get your Apple Pay banner/prompt going.

In general, we will shy away from adding attributes that are specific to non-web viewers if we can help it. The exception to this rule is when it is necessary to help smooth over some kind of UX issue related to the native viewers for consistency or compatibility purposes.

So, if it's possible to configure Quick Look by manipulating just the URL of the `.usdz` file, that is probably what we will recommend folks do, and we will not add extra attributes to make it easier to read.

Eventually, we will offer similar customizations for WebXR-based AR and other native viewers (such as Scene Viewer) may also adopt such features. If there are areas where we all implement the same features and a generalized configuration makes sense, that will be the time we choose to adopt a `<model-viewer>`-specific attribute.

> allow passing a callback function in for the "message" event that tapping on the Buy button or custom banner will trigger, and have the eventListener bind to the new anchor, and then fire the callback with the event that comes in.

This seems like something we should make easier for the user. Instead of adding a listener to the anchor directly, `<model-viewer>` can forward `message` events from itself in a psuedo-bubbling fashion. The main question I have here is, should we dispatch a `message` event or a `quicklook-message` event? I am leaning towards the latter because `message` is very vague and is already used elsewhere in the DOM and `<model-viewer>` (see `modelViewer.worklet`).

Dispatching our own event from `<model-viewer>` would allow folks to create a 'callback function for the "message" event' the same way they do for any other event: `modelViewer.addEventListener('quicklook-message', (event) => { /* ... */ });`.

**Comment by rmhall** [comment]
@cdata my pleasure - I've been using the component for a while and this particular functionality got a lot of press yesterday, and is a perfect fit for some of my needs, so thought I could give a little back.

Appreciate the insight and that makes total sense - I wasn't actually clear on wether what OI had proposed made sense for the overall goals of the project - it just seemed like a nice way to keep things easy/legible - but agreed, that part can just be part of the overall url for the existing attribute. Totally fine with that and makes sense to only extend things further when there is more parity across all the targets and a mutual benefit.  Thanks for the feedback!

Yes, absolutely, if you could bubble back up the event on the component or dispatch the event directly, that is much preferred. It was late last night and I was looking for the quick path just to validate it was possible to work something in - but after some sleep and reading your notes, this that is clearly a much better approach :). And yes, a quicklook specific event name is fine, I literally just took the example from the Apple documentation I referenced where it dispatches a "message" event and didn't realize there were already message events being leveraged in the compoent.  It looks like in the data property of the event, is simply passing a value of "_apple_ar_quicklook_button_tapped".  I think as long as we know someone interacted with it by tapping - the event name or other properties are all secondary. Just need to know someone tapped it.  Just for the sake of things potentially changing, or additional values coming in the future, I'd still bubble up the properties of the original event - say for example they add support for a press and hold, or a swipe or some other item, like the double-click the button to confirm or some other action, like oh they clicked to change modes to AR instead of model, or we got the click that they exited this mode and are back to the main component view - it won't necessarily need to be re-worked again.    Just some thoughts - but thanks again for the reply, feedback and consideration! :)

**Comment by FilipK268** [comment]
Is there any way to fire the callback at this point in time? Using the code snippet provided by apple doesn't seem to be working.

**Comment by hybridherbst** [comment]
@elalish do you have any ETA for when this could happen? I see you moved it into To do, one step in the right direction :)

We're also currently running into this issue. I tried "hacking" around the existing model-viewer, but it seems the main issue for that is that the <a> tag that's used for invoking QuickLook is never added to the DOM and thus no event bubbling occurs from it and it seems it's not accessible in any way. Or are you aware of a way to access an element that has not been added to the DOM in the same/next frame from outside model-viewer? Alternative workaround would probably be to construct the a tag ourselves on ar-button click and invoke that, but that seems like duplicating a lot of existing code.

**Comment by elalish** [comment]
@hybridherbst There are several things being discussed here, so could you spell out exactly what you need? Am I correct that you can already customize iOS by adding # info to the `ios-src` attribute? Is all that's left to intercept an event and pass it out? 

I can't promise how soon I'll get to it; it's important, but so are a number of other things. Is there a chance you'd be up to trying a PR?

**Comment by charpstar** [comment]
@hybridherbst Seems to work for me. In the openIOSARQuickLook function, I added 
 anchor.setAttribute("id", "modelView");
 document.body.appendChild(anchor);

and now it's accessible from the event bubbling.

**Comment by hybridherbst** [comment]
@charpstar yes, but that would be modifying source (which I'm trying to avoid right now because there's issues with building / developing on model-viewer on both Windows Desktop and inside VMs running on Windows, which would add a lot of technical debt).

@elalish the above would probably be all that's needed for a "quick hack" solution; better would be a proper event as cdata outlined above. 
A more structured description of the issue:
- QuickLook overlays (similar to link/title etc. for SceneViewer) can be configured through the ios-src, which works fine
(on Safari; there's issues on Chrome but that's a different story and I still have to report a bug for it)
- when a link is clicked, instead of directly opening the link (as SceneViewer does), QuickLook does a callback into the original page, passing a special "message" to the a tag that invoked QuickLook. This allows for arbitrary callbacks (e.g. actions on the page, opening links, ...)
- those callbacks are currently impossible to intercept, since the interim a tag is not added to the DOM but just clicked and then disappears into, I don't know, JavaScript garbage collection nirvana?
- this currently makes it impossible for us to have feature parity between SceneViewer and QuickLook in regards to such overlays (e.g. simple text + link)

**Comment by hybridherbst** [comment]
I think a similar issue is https://github.com/google/model-viewer/issues/1314.
@elalish yes, all that's left is the ability to intercept the event. Not sure if that's in reach for my capabilities, though (I tried to do a PR in the past but was blocked because the model-viewer build pipeline didn't really work on Windows). I do think as @charpstar said it's a pretty small change though!
