### ISSUE TITLE
@types/webgl2 dependency conflicts with TS built-in types for WebGL

### ISSUE THREAD

**Issue by MugOfPaul** [google/model-viewer#1047]
### Description

I tried adding @google/model-viewer to my typescript project. Because there's a dependency on @types/webgl2, it causes this build error. A pretty good [summary of the issue is here](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/40995).

```
node_modules/typescript/lib/lib.dom.d.ts:16532:11 - error TS2430: Interface 'WebGL2RenderingContext' incorrectly extends interface 'WebGLRenderingContext'.
  Types of property 'clearBufferfv' are incompatible.
    Type '(buffer: number, drawbuffer: number, values: ArrayLike<number> | Float32Array, srcOffset?: number) => void' is not assignable to type '(buffer: number, drawbuffer: number, values: ArrayBufferView, srcOffset: number) => void'.
      Types of parameters 'values' and 'values' are incompatible.
        Type 'ArrayBufferView' is not assignable to type 'ArrayLike<number> | Float32Array'.
          Type 'ArrayBufferView' is missing the following properties from type 'Float32Array': BYTES_PER_ELEMENT, copyWithin, every, fill, and 22 more.

16532 interface WebGL2RenderingContext extends WebGL2RenderingContextBase, WebGL2RenderingContextOverloads, WebGLRenderingContextBase {
                ~~~~~~~~~~~~~~~~~~~~~~


Found 1 error.
```

**Comment by cdata** [comment]
@MugOfPaul thanks for the report! I investigated this briefly because it rang a bell. I found [the originating discussion](https://github.com/google/model-viewer/pull/880/files#r346485394) where this was added. It sounded like the fix may have arrived in a Three.js or TypeScript update, and sure enough it seems like we can now remove this dependency. I was about to put up another small change so I piggybacked a fix for this onto that PR: https://github.com/google/model-viewer/pull/1048

We will probably cut a v0.9.1 release this week, which should include this change 👍
