### ISSUE TITLE
Multi-layer glass transparency rendering regression

### ISSUE THREAD

**Issue by cdata** [google/model-viewer#1059]
We received a report from a user that a model that displayed layers of glass has a rendering regression as of v0.9.0. The model in question can be found about half-way down the page on https://amadeus.design/en/discover/, where it is being rendered by `<model-viewer>` v0.7.2.

Before and after renders of the model follow:

v0.7.2 | v0.9.0
------|-------
![image](https://user-images.githubusercontent.com/240083/75564058-6bf32300-5a19-11ea-9170-790fb64f3b44.png)|![image](https://user-images.githubusercontent.com/240083/75564047-672e6f00-5a19-11ea-8de7-52b06aea3119.png)

The user suspected that our change to "truly transparent" backgrounds is at fault, and given that this seems blending related, that seems like a good guess to me.

**Comment by elalish** [comment]
I believe this is by design, as our rendering of transparent objects was quite broken in v0.7. I don't see anything wrong with the v0.9 one, simply that it's more opaque. This is probably because we used to not render the back sides of transparent objects at all; I imagine cutting the opacity in half would probably get it back to where it was. Unfortunately transparent rendering is iffy in all real-time renderers and there's still some debate even in glTF as to what the spec means.

**Comment by cdata** [comment]
@elalish while you are investigating, would you be willing to suggest a mitigation or workaround for the issue?

**Comment by cdata** [comment]
Marking this as wontfix for now.
