### ISSUE TITLE
After 12 hours, the animation begins to freeze.

### ISSUE THREAD

**Issue by Vatanay** [google/model-viewer#1074]
I'm trying to use a model-viewer (astronaut model) on the latest version of chromium-browser. After 12 hours, the rotating model freezes every few seconds. 

Modal is working smoothly only when I open a new chromium-browser. I also tried to refresh to tab but it does not fix the issue.

Any idea?

**OS:**  Windows
**Model-viewer Version :** 0.8.0

**Comment by soraryu** [comment]
I've seen this before after leaving a model-viewer website on after work, it was very jittery in the morning. Can't remember if refresh fixed it though.
But I'm curious about this as well because we're planning to use model-viewer for some museum exhibits, were a web page might be open for a long time.

**Comment by cdata** [comment]
Oh, interesting. Thanks for reporting @Vatanay and confirming @soraryu . I wonder if this is a precision issue, and maybe if we need to reset the rotation after it exceeds some upper threshold...

**Comment by soraryu** [comment]
I've also seen this today after switching tabs - refresh page (smooth), switch tab, switch back, really jittery. But I wasn't able to reliably reproduce it unfortunately.

**Comment by Vatanay** [comment]
@cdata thank you for your interest.

I tried another scenario today, I tried to create a 3D model slideshow with model-viewer. I swapped model every 15 seconds in UI,  after a while, model-viewer stopped working and WebGL starts to throw an error.  

**WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost**

**Comment by cdata** [comment]
@Vatanay thanks for the report. Would you be willing to create a minimal test case of this on Glitch?

I understand that some models may not be shareable due to their proprietary nature, but if you can give us details about the models (size and complexity) you are using and/or the `<model-viewer>` configuration you are using, that would be very helpful.

**Comment by Vatanay** [comment]
Hi @cdata, I placed the line of code shown below into my HTML file.
`<model-viewer src="demo-1.glb"  style="height:250px" id="object_preview"></model-viewer>`

In the same HTML file, I change src attr of model-viewer every 20 seconds with this jQuery code block.
```
setInterval(function(){
  $('#object_preview').attr('src', NEW_CONTENT);
},20000)
```

I am only displaying **3 GLB** files and I swap them with **NEW_CONTENT** variable but after few hours, the browser throws that error which I shared before : _WebGL: CONTEXT_LOST_WEBGL: loseContext: context lost_

**Comment by cdata** [comment]
@Vatanay thanks for the update. I can't promise we'll be able to reproduce the error, but I'll set up an experiment and give it a shot 👍 

BTW, can you share any info about the hardware that you are using when you experience this error?

CCing @elalish / @stevesan who recently collaborated on a fix for a Windows driver bug that led to contexts being lost.

**Comment by stevesan** [comment]
Happy to help. The issue we fixed was immediate context loss.

@Vatanay have you done this with other 3D viewers? ie. ran them for many hours, and do they work fine?
