### ISSUE TITLE
deleyed Interaction start on safari when on internal gpu? (automatic switch enabled and no external monitor attached)

### ISSUE THREAD

**Issue by koch-crsd** [google/model-viewer#1083]
Hi Guys, I've noticed that the interaction on safari on macOS seems to be very delayed to start when first time starting to "click" and then immediately "drag" around...

This seems only be affected if "on my machine" I have no external monitor attached and also within settings the "automatic gpu switch" activated. So when it runs on the internal Intel GPU instead of the Radeon... My Internal is: => Intel HD Graphics 630 1536 MB

<img width="793" alt="Bildschirmfoto 2020-03-13 um 09 57 09" src="https://user-images.githubusercontent.com/47377645/76605597-0458cf80-6511-11ea-9a40-cd0683ad3f6b.png">

So, steps to reproduce:

1. Make sure you're on the internal gpu and no monitor attached
2. With Safari, visit: https://modelviewer.dev
3. wait until the turntable rotation begins
4. click and immediately start dragging around...
5. you'll notice a sometimes long delay until the model starts follows your interaction

re-appears if you then mouse-up and wait until turntable begins... try again..
but I noticed this also on integrations where not turntable autoplay is active..

Safari: 13.1
macOS: 10.15

This may be more related to Safari/macOS problem itself?
It feels the click interaction start very delayed...

Small video:
https://www.dropbox.com/s/492zjtpeaaunt13/Bildschirmvideo%20aufnehmen%202020-03-13%20um%2010.17.19.mov?dl=0

### Browser Affected

- [ ] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Helios
- [ ] IE
- [X] Safari

### OS

- [ ] Android
- [ ] iOS
- [ ] Linux
- [X] MacOS
- [ ] Windows

### Versions
same that is currently online at https://modelviewer.dev

**Comment by cdata** [comment]
@koch-crsd thanks for reporting! And, I apologize for the delay in getting back to you. Due to COVID-19-related events, we are currently operating with diminished resources so everything is backed up.

Unfortunate, I was unable to reproduce the issue (using the same GPU, event). Here is a screen recording that I took after finally getting my laptop to switch to the Intel GPU:

![2020-03-24 09-23-55 2020-03-24 09_28_12](https://user-images.githubusercontent.com/240083/77451816-6a1b4600-6db2-11ea-9280-162e96322446.gif)
 
![image](https://user-images.githubusercontent.com/240083/77451764-596ad000-6db2-11ea-98dc-41dae8d32542.png)

I wonder: could you maybe have other applications running at the same time that are using the GPU?

Or perhaps you have extensions installed that could be interacting with (or otherwise effecting) `<model-viewer>` somehow?
