### ISSUE TITLE
Feature Request: Ability to specify exact link passed into SceneViewer intent

### ISSUE THREAD

**Issue by hybridherbst** [google/model-viewer#1085]
### Description

We're currently leveraging some (notably undocumented) features of SceneViewer by passing in more URL parameters. This includes
- title - different than what model-viewer automatically does since we need multi-language support and also since that title can differ from the alt text in some cases
- link - by default model-viewer passes the link to the page where the model-viewer is into SceneViewer intent. We don't want that and instead want to link to other places. Back button already leads back to the webpage.
- sound - we're playing back sound in SceneViewer and also pass that with the src URL.
- glb src itself (see #1084)

This in some cases produces duplicate query parameters with potentially undefined behaviour (and model-viewer rightfully warns about that). So the feature request here would be to allow overriding the URL passed into the Intent including all query parameters.

Currently, as a workaround, we're changing the "src" attribute right when the user clicks the AR button, but that obviously leads to model-viewer also fetching the GLB again (since it's a "new" URL).

**Comment by cdata** [comment]
@soraryu thanks for the request. What if we dispatched an event just before triggering Scene Viewer that gives you a way to modify the `intent://` URL before we trigger it?

For example:

```typescript
modelViewer.addEventListener('scene-viewer-intent', (event) => {
  const intentURL: URL = event.detail.intentURL;
  // modify intentURL and whatever it changes to will be used to trigger Scene Viewer
});
```

**Comment by soraryu** [comment]
Sounds good. I'm not super sure about the details though - there might be some parts of the intent url that _should_ be internal (e.g. the actual "intent" stuff) and some parts (e.g. what's passed into the intent as parameter) that we should be able to modify.
(e.g. so that in case the internal intent format changes the above would still work in future model-viewer versions).

**Comment by cdata** [comment]
My thinking is that we would just expose exactly what we intend to invoke Scene Viewer with (that is, the raw intent as a `URL` instance). The reason behind this is that ultimately, Scene Viewer will land new features (including significant changes to their intent scheme) and it will take time for us to catch up to those. Giving folks full access to the raw intent this way gives them an opportunity to work around any latency while we catch up. It also gives you a better way to workaround e.g., #1084 while we figure out how to land that feature.

**Comment by soraryu** [comment]
OK, makes sense. Ideally this would go along with a slight change in documentation, e.g. specifying what the default intent does so it's easy for people to adjust it.

(there'll still be a slight risk that SceneViewer gets updated, model-viewer updates as well, people update model-viewer, now their code doesn't work anymore since they are overriding with a wrong intent - but documentation about what exactly the used intent is would help)

**Comment by cdata** [comment]
This is semi-related to #588

**Comment by elalish** [comment]
I believe our handling of query parameters is now working properly.
