### ISSUE TITLE
Update to the latest Scene Viewer intent scheme

### ISSUE THREAD

**Issue by cdata** [google/model-viewer#1097]
[Scene Viewer has an updated intent scheme](https://developers.google.com/ar/develop/java/scene-viewer#3d-or-ar). We should update to use it. In addition to being the likely path forward for configuring new Scene Viewer features, it appears to offer the ability to specify parameters like `title` and `link` without using the query string in the model URL.

**Comment by soraryu** [comment]
Very looking forward to this.
As a note, through this docs I finally found out there's a mode=ar_preferred! Honestly **I think this should be default**, showing the object first does not make much sense since users have _always_ seen this before when using model-viewer.
(Note: already works by appending `&mode=ar_preferred`, but would be nice to have that default)
