### ISSUE TITLE
low version google chrome(my version is 73) is not supported,how can I support it

### ISSUE THREAD

**Issue by gexingfeiyang** [google/model-viewer#1109]
### Description
I can use it correct in new version google chrome,but in low version,the glb suffix file can not show,when I upgrade the low version to new version,it can show again,how can I do in the low version google chrome

### Browser Affected
- Chrome

### OS
- Windows

### Versions
Chrome:73

**Comment by cdata** [comment]
@gexingfeiyang we actively support the last two versions of every major browser. If there is a reason why you cannot upgrade, please let us know so that we can consider whether or not we should extend support.

To be honest with you, it is unlikely that we will go out of our way to support a Chrome version that old. However, if you explain your use case a little more and also share an example / demo / model that fails in old Chrome, then I would be happy to consider the issue with you and give you a more clear answer as to whether or not you can use old Chrome.

**Comment by artob** [comment]
Something to note is that developers working with the Android emulator tend to have old Chrome versions by default. I was trying to get the model viewer working in a WebView on an Android 10 image, but that didn't work out; as it turned out, that image shipped with Chrome 74:

![Screenshot_1589902854_cropped](https://user-images.githubusercontent.com/4963/82347572-7dd4d880-9a00-11ea-8bb0-b5ed8b764dda.png)

**Comment by artob** [comment]
@cdata Where might one find documented the oldest Chrome version that v1.0.0 supports?

**Comment by elalish** [comment]
@artob We don't document that anywhere because we don't have enough test coverage to be certain. More than likely it won't stop completely, but simply have more and more bugs the further back you go. As stated above, our test coverage is generally for the most recent two versions.

**Comment by artob** [comment]
@elalish The failures I have seen (with the bundled stock Chrome version on Android 10 VMs, as mentioned above) produced just a blank white page with no overt indication of anything wrong other than the content just missing.

Is that the intended failure mode for ancient Chrome versions (Chrome 74 in that case), or might it perhaps be useful to show some failure indication similar to broken image tags?

Also, even if it's not possible to pinpoint the exact version where all this no longer works, would it at least be possible to document a known-good version where it all _certainly_ does work?

**Comment by elalish** [comment]
@artob Indeed, those things would be helpful. I'd be more than happy to accept a PR, and if that's too heavy a lift, if you want to test some chrome versions and put the results here, I can put them into our docs somewhere. The biggest challenge is it will tend to be a moving target.

**Comment by Muhammad-Faizmf** [comment]
is there any way to disable Scale on AR Mode

**Comment by elalish** [comment]
https://modelviewer.dev/docs/index.html#entrydocs-augmentedreality-attributes-arScale

**Comment by Muhammad-Faizmf** [comment]
I have integrated this model viewer plus in android application everything works fine but the ar-scale does not work. I have also make changes in packages but nothing works. your response will be appreciated.

**Comment by Pradeep2535** [comment]
I have a problem with my app. Its working fine in android emulator, but when i deploy it by downloading the apk the model is not loaded,rather than a blue colour loading indicator keeps on loading.
![WhatsApp Image 2024-04-28 at 17 25 40_c6ec62b8](https://github.com/google/model-viewer/assets/117376703/f860bae7-49ce-46d3-8f1a-36d2dd26236b)
