### ISSUE TITLE
Remove link and title from SceneViewer

### ISSUE THREAD

**Issue by elalish** [google/model-viewer#1143]
I propose removing the optional link and title from our SceneViewer intent, as all they do is create a more busy UX (the extra bar at the bottom), and add a third button (visit) to the already existing top-left X and bottom-left back arrow that all do exactly the same thing (return to model-viewer, as mentioned in #1085). Additionally, if someone neglects to set the alt text, displaying it in SceneViewer makes the error more glaring. 

![image](https://user-images.githubusercontent.com/1649964/79169529-899a0300-7da1-11ea-8098-a45c3b9ff101.png)

**Comment by cdata** [comment]
I think we should make this configurable. The default UX may not be especially topical in a lot of cases, but it was designed that way in collaboration with the Scene Viewer team.

**Comment by cdata** [comment]
So, there ought to be some way to disable it if that is desired, or customize the values of both the label and the link. In cases where we can infer the values, there isn't really any reason to stop doing that.

**Comment by elalish** [comment]
I agree about configurability, which is #1085. I still don't like the current behavior even as a default though; that visit button opens a webview of Chrome, so you end up someplace that looks similar but isn't.

**Comment by cdata** [comment]
I think we can all get behind the app-based approach with web views being sub-par and not great for users. IMO, the best way to address that is for WebXR to propagate and become ubiquitous, so that we can reset the general community's expectations of what AR means in conjunction with their own content.

**Comment by soraryu** [comment]
@cdata @elalish 
Just my 2ct: we had a couple cases where we actually need to have title and link, and the link does **not** lead back to where the user came from.

Most notable of those is the usecase of "direct QR links" which basically
- are opened when scanning a QR code
- are model-viewer pages
- that immediately activate AR if possible
- that show the model-viewer page as fallback if not possible
- that, in AR, link to some other page (e.g. an event, or a webpage explaining what you just looked at).

I agree that at some point WebXR will allow to configure that better, but not today...
Also note that QuickLook pushes this "single button in AR" heavily for their [buy-a-product-in-AR-experience](https://developer.apple.com/documentation/arkit/adding_an_apple_pay_button_or_a_custom_action_in_ar_quick_look). Not that I find that great but wanted to point it out.

**Comment by milesgreen** [comment]
Just to add +1 to this. 

Agreed with above that ideal would be to have this configurable.

Ability to turn on/off. Ability to explicitly define `title` and `link` values. 

Or, absence of explicitly defined values defaults to off. 

Potential use case I'm thinking of is where the AR view is part of a user journey that you want user to continue forward with, rather than step back. 

EG. User views a product summary. User choses to see product in AR. The SceneViewer banner can then have a call to action to "Learn More", and the link directs to a specific URL for full product details.

Thus, I'd prefer to have an explicit `title` param to be able to set that text rather than pass from the ModelViewer `alt` tag (that's what it does now, right?) as this is potentially a different context.

I'd like to have the `link` URL configurable, as it may be desirable for this to be something other than the page the ModelViewer launched from. 

Alternatively, pass the CTA click event back to ModelViewer, but that's a change to SceneViewer I guess.
