### ISSUE TITLE
can model-viewer used in android?  i have CORS-restricted problem.

### ISSUE THREAD

**Issue by whitebird101** [google/model-viewer#1148]
can model-viewer.js used in  android app? 
when i try use model-viewer.js in my android app, and Access the JS file from local file system.
the following error occurs:
`I/chromium: [INFO:CONSOLE(0)] "Access to Script at 'file:///android_asset/model-viewer.js' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.", source: file:///android_asset/test.html (0)`
what can i do if i want use this js in android app?

**Comment by cdata** [comment]
@whitebird101 yes, we absolutely can be used on Android. However, you must work within the sandboxing rules of the browser, and this includes cross-origin restrictions.

My recommendation is to run a local web server and host `test.html` and `model-viewer.js` there, so that you can be sure that the origins are configured as you intend, and that any CORS headers you set are correct.

For CORS issues related to serving models, I would also recommend referring to the discussion here: https://github.com/google/model-viewer/issues/1015

**Comment by whitebird101** [comment]
@cdata thanks for your reply！But, specific to my project, in many cases, there is no network support, no WIFI. so, my app must run locally。in this case, i want know that can model-viewer.js  be used on Android? without  any local web server or host.
can model-viewer.js  be used just like JQuery.js? put the JS file in local folder，and write a HTML file , import model-viewer.js  through <script> tag, and then display a 3D model through <model-viewer> tag?
thanks again!
