### ISSUE TITLE
Video as background

### ISSUE THREAD

**Issue by sressler** [google/model-viewer#1158]
### Description

This is a feature request, (if this is not the right place please direct me), I'd like to be able to have a video as the background to a model-viewer scene. In aframe this is done with something like: 
       
 \<a-entity id="imvideo" position="2 1 0" immersive-video="type: 360_mono; source:https://my.video.com/videofile.mp4"  loop   crossorigin="anonymous">

I see there can be a  background-image, so replace that with a video source..easy peasy right ;-)
thanks!

**Comment by cdata** [comment]
Thanks for filing the requested @sressler !

Speaking practically, this is something that should be possible for us to implement. A related but distant consideration is that glTF has no specific affordance for video (that I know of). 

Performance-minded, adaptive video streaming is a deep topic and it might be worth us doing an investigation of how the `immersive-video` A-Frame component is implemented before we agree to build support for this into `<model-viewer>`. If it is possible for us to do something useful with a provided `<video>` element, that might be a reasonable approach as it would allow us to philosophically "wash our hands" with regards to performance questions.

@elalish this seems like one you might have a well-formed opinion on 👍 

Note: this issue was filed as a continuation of the discussion in https://spectrum.chat/model-viewer/general/cool-stuff-and-question~b8734ee4-3a3c-49b9-8756-992c2203b1a1

**Comment by elalish** [comment]
Seems like this would be possible by using https://threejs.org/docs/index.html#api/en/textures/VideoTexture with Equirectangular mapping as the background. I definitely wouldn't want to use it for the environment lighting though, as that would be far too much computation. @sressler Would that be a reasonable compromise?

**Comment by soraryu** [comment]
Would be a good time to revisit the resolution restrictions on the background image I think (#912).

**Comment by elalish** [comment]
At the current level of interest, I don't see us implementing this.
