### ISSUE TITLE
Refused to load the image blob

### ISSUE THREAD

**Issue by efsjouw** [google/model-viewer#1162]
### Description

Trying to load my model from the glitch.me url now gives me this message, while previously it worked fine?

`Refused to load the image 'blob:<URL>' because it violates the following Content Security Policy directive: "default-src * 'self' 'unsafe-inline' 'unsafe-eval' data: gap:". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback.`

Also, the thing is that the intent link still works with this link but the model-viewer does not?

#### Live Demo

`    <div class="card card-outline">
      <div class="card-content card-content-padding">
        <div class="card-header">City</div>
        
        <model-viewer
          poster="./img/cycles/city_720.jpg"
          src="https://nickel-pushy-iris.glitch.me/assets/City.glb"
          ios-src="https://cdn.glitch.com/36cb8393-65c6-408d-a538-055ada20431b/Astronaut.usdz?v=1569545377878"
          alt="Cortes"
          shadow-intensity="1"
          preload camera-controls
          interaction-prompt="auto"
          auto-rotate magic-leap>
        </model-viewer>
      </div>
      <div class="card-footer">
        <a href="#"></a>
        <a href="intent://nickel-pushy-iris.glitch.me/assets/City.glb#Intent;scheme=https;package=com.google.android.googlequicksearchbox;action=android.intent.action.VIEW;S.browser_fallback_url=https://developers.google.com/ar;end;" 
            class="col button button-large button-raised button-fill external yellow-button">
            Bekijk de fiets live
            
          </a>
          <a href="#"></a>
      </div>
    </div>  `

### Browser Affected

- [x ] Chrome
- [ ] Edge
- [ x] Firefox
- [ ] Helios
- [ ] IE
- [ ] Safari

### OS

- [ ] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### Versions
- model-viewer: v0.10.0

Also why does my html code blocks keep formatting incorrectly...

**Comment by efsjouw** [comment]
Alright it was because of this <meta http-equiv="Content-Security-Policy"> at the index page.

**Comment by cdata** [comment]
@efsjouw thanks for filing. It sounds like maybe you were able to figure out the problem for yourself. Can you confirm if you still have an issue?

**Comment by efsjouw** [comment]
Mh yeah i can just disable the meta tag, but how to deal with this properly?
Put something like `model-viewer-src 'self' blob: data:;` into content?

**Comment by cdata** [comment]
@efsjouw it sounds like your CSP settings are too strict to allow you to load the files across origins, possibly including as `data:` URLs. You may have to loosen your CSP settings in order to allow for `<model-viewer>` to work correctly.

Adding something along the lines of `image-src data:` to the CSP header should address the error you original posted (see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/img-src).

`<model-viewer>` does not have any specific integration or syntax to help with CSP. Under the hood, it is just loading JSON, binary and images with `fetch` and/or `XMLHttpRequest` like any other script. In some cases, it also loads things using `data:` or object URLs. Your CSP needs to be configured accordingly.
