### ISSUE TITLE
lighthouse: lighthouse statistics going crazy

### ISSUE THREAD

**Issue by felixhaeberle** [google/model-viewer#1222]
### Description
The model-viewer library in general has performance issues which can be observed by the Lighthouse scoring. On every site I embed it, it ruins the Lighthouse score single-handed and it gets unrealistic time-to-interactive of 20sec.

![Screenshot 2020-05-23 21 09 04](https://user-images.githubusercontent.com/34959078/82738725-3a4cd800-9d3a-11ea-8e5c-e8c13b2ebdd6.png)

#### Live Demo
https://modelviewer.dev/

### Browser Affected
- [X] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Helios
- [ ] IE
- [ ] Safari

### OS

- [ ] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### Versions

- model-viewer: latest
- three.js: latest

Thanks very much for your effort in this project. I would be very happy if you could fix this bug at the library level, because that's not specific to the model-viewer websites but to all pages which use the model viewer.

**Comment by elalish** [comment]
Thank you for pointing this out; we definitely have our work cut out for us in this area, due to the high network, CPU and GPU cost of 3D rendering. Our docs pages are not ideal candidates, as they are designed primarily for ease of understanding, rather than load performance. A better example might be: https://www.khronos.org/blog/view-a-gltf-model-in-ar-on-android-without-leaving-your-browser, which performs a bit better:

<img width="1678" alt="Screen Shot 2020-06-01 at 4 17 02 PM" src="https://user-images.githubusercontent.com/1649964/83463620-6a276a00-a423-11ea-8908-50c9121db526.png">

Still, there is plenty of room for improvement, especially getting more 3D work off of the main thread. We fully intend to make progress in performance.

**Comment by elalish** [comment]
So, we did some work to fix our bundle size and also to clean up our lazy-loading, which seems to have helped a fair bit. But most importantly, I've now added some [examples](https://modelviewer.dev/examples/lighthouse.html) demonstrating how to best set up model-viewer on your website for good lighthouse scores. I'm closing this since we've hit 100's across the board even on mobile, but rest assured we'll continue to keep an eye on these scores and improve them where possible.
