### ISSUE TITLE
Is there a way to add buttons to be able to switch materials/colours on the model?

### ISSUE THREAD

**Issue by ajth789** [google/model-viewer#1243]
Looking to add a few buttons to the model viewer so a user can select a color and see the model change in real time. 

How would I best approach this? I can't find a reference to this use case in the documentation.

**Comment by elalish** [comment]
@cdata has just been building this functionality and it will be more complete in our upcoming release for v1.0. We haven't publicized this much yet since it is in progress, but you can see an example here: https://modelviewer.dev/examples/scene-graph.html

Any feedback you have for us would be much appreciated.

**Comment by ajth789** [comment]
This is really helpful and the demo works well on my pixel 3.

Is there anything in the roadmap to be able to do the same with different
elements of the model? For wxple, changing the helmet, shoes, etc.

Cheers
Ash

**Comment by elalish** [comment]
We're definitely interested in this, but with limited resources it may be awhile before we can build it. If you're interested in contributing, I'd be happy to walk you through how we see this fitting into our API and architecture.

**Comment by loeffel-io** [comment]
Would love to see this feature +1

**Comment by elalish** [comment]
I forgot to close this; this feature was released in v1.1. See https://modelviewer.dev/examples/scene-graph.html

**Comment by Wulff2099** [comment]
Hello, i try to change the color of a model, its work fine but in iphone using a model .usdz file is all white.

**Comment by elalish** [comment]
@Wulff2099 yeah, you're out of luck with usdz; that's an apple format and model-viewer doesn't operate on it. We're pushing WebXR for AR, since that gets around all this incompatibility, but until Webkit supports it you'll be stuck with less customization on iOS. You might be able to achieve something similar using a .reality file instead of .usdz, but I'm not sure, and it'll definitely be independent.

**Comment by Wulff2099** [comment]
Thanks elalish for the quick answer

**Comment by MrSounds** [comment]
Is there an attribute to change the default color on the model, like the buttons in the demo does?
I've tried "data-color" in the model-viewer attributes, but it didn't work.

**Comment by elalish** [comment]
No, the more advanced features are JS-only, so you'll have to follow the demo code.
