### ISSUE TITLE
Exported gltf from three.js only showing in AR, not in 3D

### ISSUE THREAD

**Issue by nick-sp** [google/model-viewer#1244]
I exported a model in gltf via three.js and put it in a website using model-viewer.

The model is not showing up in 3D (nothing appears) regardless of device / browser, but when visiting from mobile the AR mode works just fine.

The model also loads normally on the scene-viewer-preview.

Does anyone have a suggestion on what might be happening?
Thank you

**Comment by somepablo** [comment]
For me it's just the opposite. I can see models in the 3D view, but not in AR from any android phone.

When loading the AR view, an error message appears: "Couldn't load object".

Android log prints it cannot find the GLB file because server returns a 404. Looking at the URL it seems that's because it is stripping all query string params put on the "src" url of the model-viewer. 

This is happening since some hours ago, same models that 2 days ago were working. Not sure if its a thing with the last ModelViewer release or with android SceneViewer, but I'm not seeing any recent update.

**Comment by elalish** [comment]
@nick-sp Can you remix our [Glitch](https://glitch.com/edit/#!/model-viewer) to demonstrate your problem? I'd be happy to take a look. Since model-viewer is built on three.js, if the three.js editor is making a file we don't like, it may be a three.js bug.
