### ISSUE TITLE
Regression: with WebXR now the default, it should be on par with SceneViewer

### ISSUE THREAD

**Issue by hybridherbst** [google/model-viewer#1270]
### Description

Since WebXR is now the default ar-mode, I think the functionality needs to be at least on par to the previous behaviour.

1. **2-finger rotation on the model does not work.**
  It works outside the model, with one finger only, while SceneViewer behaviour allows rotation with two fingers, which is crucial for larger models.
1. **no built-in way nor demo to show a similar label + link as SceneViewer+QuickLook.**
  I understand this can be custom-made, but given that this is built-in in both SceneViewer and QuickLook I think it should be built-in/default for the WebXR implementation as well. Ideally there's at least a demo for it, even better would in my opinion be if the default behaviour shows a title and link.
1. **no built-in way to capture pictures or videos** 
  I understand that this is also something that "can be built in js now" but I'd argue that model-viewer should provide that functionality by default to be on par with SceneViewer and QuickLook.
1. **UX regression in onboarding of users to AR**
  With SceneViewer, there's a one-time permission dialogue with a nicely crafted, nice looking onboarding flow. 
  With model-viewer WebXR, this is replaced by no onboarding + an ugly and scary browser default permission dialogue. 
  I don't have a good idea how to solve this; but I think that since model-viewer WebXR is effectively on track to replace SceneViewer onboarding UX should not be pushed onto devs implementating model-viewer.

#### Live Demo
https://modelviewer.dev/examples/webxr.html

### OS

- [X] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

**Comment by elalish** [comment]
Thank you for the feedback.

1) Yes, I hadn't prioritized it because I found two-finger rotation in SceneViewer a bit awkward and not discoverable. But yes, the goal is parity.
2) Agreed, I plan to make a demo for this. Not sure about making it automatic; I'd certainly welcome a PR along those lines.
3) I've actually been hounding my webXR colleagues about this for more than a month now. We are actually missing a platform API for this; I'm hoping we can close that gap soon and as soon as one is available, I will certainly implement it here.

Anyway, remember you're welcome to set `ar-modes="scene-viewer webxr quick-look'` if you prefer the old behavior.

**Comment by hybridherbst** [comment]
Thanks for replying! Good to know you're onto these.

The two-finger rotation is really important, currently WebXR in that sense doesn't take advantage of already learned user behaviour from touchscreens (a lot of our usecases involve being close to a model and still being able to rotate it, like architectural miniature models).

Just to clarify, I'm super happy that WebXR now works! Currently it just means that for the foreseeable future we will have to kinda maintain 4 platforms instead of 3 for showing a single model (in-browser model-viewer / in-AR model-viewer WebXR / SceneViewer / QuickLook) and for that I'm of course looking at the "lowest common denominator" between these. model-viewer WebXR is an outlier in this sense as it's the only AR one that doesn't provide basic labelling out of the box right right now.

**Comment by elalish** [comment]
@hybridherbst Can you describe what you mean by onboarding?

**Comment by hybridherbst** [comment]
Sure. If you reset the cache and data for "Google Play Services for AR" and click the AR button (if WebXR is off), you'll essentially see what 90% of our users see - Google's onboarding for AR when you use it for the first time.

E.g. this: 
![Screenshot_2020-06-17-21-36-14-242_com google android googlequicksearchbox](https://user-images.githubusercontent.com/2693840/84944497-23ee2e00-b0e6-11ea-9eec-eebf8268880e.jpg)

(On device it's like a GIF, explaining the basics of AR. This is very helpful to people who are new to it.)

**Comment by elalish** [comment]
Ah, thank you. We can't really put this in model-viewer because the images and text for all languages would destroy our binary size. It would be nice to have an HTML example, but we'd need to know it was someone's first time somehow. It's a good point and I'll talk to webXR about what we could do here.

**Comment by hybridherbst** [comment]
Understood, that's why I mentioned I also don't know how to solve it, but still feel it's a user experience regression from the "old" behaviour that doesn't exactly make this more approachable to people unfortunately. 
Curious to hear what the WebXR team says about that!

**Comment by hybridherbst** [comment]
Relevant movement in the "competition":
https://medium.com/8th-wall/announcing-in-browser-video-recording-ec0c2b3d0045
