### ISSUE TITLE
HDR's configuration is not correct in babylonjs's renderer page

### ISSUE THREAD

**Issue by sun765** [google/model-viewer#1297]
### Description

In some scenarios, the HDR map looks wired. I think the problem is when loading HDR map the configuration is not set correctly. I should look into how other renderer setup hdr map and fix this problem
![Screenshot 2020-06-18 at 12 11 27 PM](https://user-images.githubusercontent.com/44676379/85045360-dc56b900-b15c-11ea-863e-679a72ad5f00.png)

**Comment by elalish** [comment]
@sun765 Could you include a golden image to compare here, to make it clearer what you mean by "weird"? Having done this before for Filament I may be able to give you some hints.

**Comment by elalish** [comment]
@sun765 It looks like the environment is rotated by 90 or 180 degrees relative to the model (which is common because standards in this space are sparse). See if Babylon has a configuration for the environment orientation. If not, then rotate the model and camera to compensate.

I would bet that 128 means a 128x128 cubemap size. We use 256 and that's what our environments are sized for, so try 256 and see if it's more similar.
