### ISSUE TITLE
Cannot import model-viewer since 1.0.0 with npm install

### ISSUE THREAD

**Issue by aarbro** [google/model-viewer#1372]
### Description

As has been reported in a few other issues (https://github.com/google/model-viewer/issues/1300, https://github.com/google/model-viewer/issues/1208, maybe others), there's been a failure to resolve the model-viewer when using `import "@google/model-viewer"`. This worked fine until 1.0.0. In my case it is a vue based project, but I suspect it has the same root cause as the React based projects in other issues. It has something to do with the underlying bundler (Webpack, in my case).

As someone suggested in other threads, you can workaround this by using a direct import to the "dist" folder: `import "@google/model-viewer/dist/model-viewer"`. While this works, it is ugly and ultimately causes another issue.

In looking at the changes in 1.0.0, I traced it down to [this change to package.json](https://github.com/google/model-viewer/commit/92111b3ac68c22508bc00edb6300404407308008#diff-f4d9494fdb27b7fe22b92831ca57b757).

First, in the "files" section, "lib", and "src" are removed and the "main" and "module" now point to a non-existent location:

```
  "main": "./lib/model-viewer.js",
  "module": "./lib/model-viewer.js",
```
I manually edited this in my node_modules to use the "./dist" and could then import successfully with expected syntax.

Obviously, the primary problem is the inability to import, but a secondary problem I have is how we generate our 3rd party dependencies from Webpack seems to depend on this, in that I no longer get the transitive dependencies (i.e. three). I do not know if lib/src are required or not, but would like them to be restored, and would probably be needed to debug correctly.

#### Live Demo
Not available.

### Browser Affected
n/a

### OS
All - n/a

### Versions

- model-viewer: v1.0.0

**Comment by elalish** [comment]
@aarbro Thank you so much for the detailed analysis! The main and module paths look like a clear bug. The reason for removing lib and src was because these contained internal functions that are not part of our stable, public API, so we wanted to discourage anyone depending on them directly. Out of curiosity, what do you use the transitive dependency on three.js for? I definitely want to package this repo in a way that is most usable, but I'm less familiar with these frameworks. 

Another problem is that our source map files didn't get published to npm last time, so I'm hoping the addition of those will help with debug.

**Comment by aarbro** [comment]
@elalish I'm don't have full understanding of this either, but we are required to have approval for any open source software we use, and it is supposed to include transitive dependencies. It is my understanding that we cannot fully rely on the dependencies listed in the package.json, so instead were getting a supposedly more accurate list of dependencies by relying on Webpack, as it will build a list based on the imports and requires in the code.

**Comment by elalish** [comment]
@aarbro Okay, so now that we only publish our bundles, they are completely self-contained (the three.js source is actually most of our bundle size). So maybe the right thing to do is move all our dependencies to devDependencies, to make it more clear that there's nothing needed.

**Comment by rana9037** [comment]
Here's a little more context on the root of the problem: we have to go through legal clearance for all code that's delivered to the client, which includes the packages we directly import into our code as well as the transitively included packages that are dependencies of the direct imports. We use Webpack to generate a license file from our imports, and that's the file we use to submit our clearing requests as it lists out all the packages delivered to the client. 

The issue in this case is that the model-viewer package was pre-bundled, and Webpack can't read a bundle. So it was unable to identify the transitive dependencies of this package.

Is there a license file for this package or a file that lists out all the packages that are delivered when the client imports model-viewer?

We didn't run into this issue with previous versions of model-viewer since those were published un-bundled.

**Comment by elalish** [comment]
@rana9037 I believe that legally the bundlers / minifiers are not allowed to remove license comments, so I believe you can find them all by searching model-viewer.js for `@license` strings.

**Comment by rana9037** [comment]
@elalish I went through model-viewer.js and searched for `@license`. I found a reference to it for `three.js` and `polymer`.  Is it safe to say that, based on this and the dependencies listed in package.json, that the transitive dependencies are `polymer/lit-element` and `three`?

```
"dependencies": {
    "@google/3dom": "0.0.1-alpha.5",
    "@types/resize-observer-browser": "^0.1.2",
    "lit-element": "^2.2.0",
    "three": "^0.117.1"
  },
```

**Comment by elalish** [comment]
Yes, that's correct, and searching those `@license` strings is the canonical way to find them. Meanwhile, I need to move all our dependencies to devDependencies, because we now package everything internally.
