### ISSUE TITLE
Scene Graph example does not work using suggested library

### ISSUE THREAD

**Issue by Atomk** [google/model-viewer#1389]
### Description

The [Scene Graph example](https://modelviewer.dev/examples/scene-graph.html) on the website does not work when loading the package with the link shown on the website's home page:
```js
<script type="module" src="https://unpkg.com/@google/model-viewer/dist/model-viewer.min.js"></script>
```

When clicking a button to change color, this message appears in the console:
`Uncaught TypeError: Cannot read property 'materials' of undefined`

This behaviour looks similar to what was reported in [this comment](https://github.com/google/model-viewer/pull/1302#issuecomment-656367205) on another issue.

#### Live Demo

https://glitch.com/edit/#!/scene-graph-bug-repro

### Browser Affected

- [x] Chrome 84.0.4147.89 (64bit)
- [ ] Edge
- [ ] Firefox
- [ ] Helios
- [ ] IE
- [ ] Safari

### OS

- [ ] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [x] Windows 10 (64bit)

### Versions

- model-viewer: v1.0.0
- three.js: ???

**Comment by elalish** [comment]
I can repro the problem your glitch demonstrates, and it's interesting because it does not repro on the docs site with either `model-viewer.js` or `model-viewer.min.js`. Can you try moving those module loading scripts up to the top of your page? It looks like it's trying to invoke our API before the custom elements have been upgraded. 

If that's it, I should change our docs pages accordingly, because that's confusing behavior. The only reason I can think that it works on our docs pages is because of the dependencies we put in for style that may be affecting the loading order.

**Comment by Atomk** [comment]
Thanks for your interest, I tried to move the two scripts (the main one and the "nomodule" one) in `<head>` and at the top of `<body>` but in both cases I still had the error.

**Comment by elalish** [comment]
I'm sorry, this is due to our docs pages being a bit confusing. They are served off of master, rather than the latest release. You included model-viewer the proper way:
`<script type="module" src="https://unpkg.com/@google/model-viewer/dist/model-viewer.min.js"></script>`
which loads the latest release, v1.0 in this case. However, the feature you're trying to use is newer than 1.0 and hasn't gone out in a release yet, though it will soon. In order to test the master version that our docs are using, change your include to this:
`<script type="module" src="https://modelviewer.dev/node_modules/@google/model-viewer/dist/model-viewer.min.js></script>`

**Comment by Atomk** [comment]
It works! I thought the documentation was related to the latest release, but I'm glad you were able to figure it out, I'll use the new link until the next release then. Thanks a lot for your help!
