### ISSUE TITLE
[Editor] How can I add an alpha texture for transparencies in the editor?

### ISSUE THREAD

**Issue by nestorchura2019** [google/model-viewer#1510]
https://modelviewer.dev/editor/
I see that I can add the other maps like occlusion, normal map etc,
but how can I add an alpha texture to make the model transparent?
![image](https://user-images.githubusercontent.com/56547770/92294596-c1dde180-eefa-11ea-8a3c-1518f50e3ece.png)

**Comment by nestorchura2019** [comment]
I found a partial solution, if I edit the texture in PS, GIMP, etc. deleting part of the photo and saving in .png with transparency, the model works with transparency (alpha) in the editor.
In three.js you can add an alphaMap for opacity, is that possible with modelViewer?

**Comment by elalish** [comment]
Keep in mind that here we're editing a glTF, which is a subset of everything three.js can do with materials. In glTF, alpha is a channel of the baseColor. Keep in mind that this isn't the best way to create transparency, as it's for things like gauze, rather than glass. There is a real glTF transparency extension coming soon that should improve this.
