### ISSUE TITLE
Some GLTF models have incorrectly shown normal maps when you zoom in 

### ISSUE THREAD

**Issue by dhruvadhia1** [google/model-viewer#1537]
### Description
Hi There,

I have two links below, Model Viewer
https://thecela.com/configurator/bjI5Y1lLT2NvemY9/QVF0PQ==/cDJBdW90PT0=

Babylon
https://thecela.com/babylon/

And when you zoom in you will see the strap shows up a bit abnormally whereas it shows fine on all zoom levels in Babylon viewer. 

Model Viewer issue with shoe strap. 
<img width="442" alt="Screen Shot 2020-09-15 at 11 28 33 AM" src="https://user-images.githubusercontent.com/70779749/93249729-994db700-f746-11ea-8497-260796146513.png">

Using the latest version of the model viewer as documented on the website.

### Browser Affected

- [Yes ] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [ ] Safari

### OS

- [ ] Android
- [ ] iOS
- [ ] Linux
- [Yes] MacOS
- [ ] Windows

**Comment by elalish** [comment]
It's hard to say for sure, as I'm getting a server 500 error on the first link, but it looks like you're not getting trilinear mipmap interpolation. This is a common problem with glTF exporters setting a non-default value for a `sampler` `minFilter`. If you load this in our [editor](https://modelviewer.dev/editor/), look at the last tab and search for `minFilter` and see if there's a value other than 9987. If so, I'd just remove that line in a text editor so that it gets the default value. I'm guessing Babylon may just not be parsing this value at all. This is a common enough problem that we may need to add a feature to our editor to fix this automatically.

**Comment by dhruvadhia1** [comment]
I do see this 

"minFilter": 9985, and I just replaced it with 9987. It seems to be looking normal now. Thanks for the quick correction. I would consider this close.
