### ISSUE TITLE
Generated screenshot is 2x the size of model-viewer's size 

### ISSUE THREAD

**Issue by karanganesan** [google/model-viewer#1666]
### Description
So lately we I have been using .toDataURL function to generate images based on model viewer. I found that images generated are twice the size of style given to model-viewer

also some odd behaviour on different MacOS versions 

Catalina Chrome - it doubles the size
Catalina Safari - it doubles the size 

Big Sur Chrome - it doubles the size 
Big Sur Safari - it's working fine like generates the exact size as model-viewer's style given (width and height)

so because of the above behaviour it might even be a browser bug, but I am not sure. or I think it's possible to do something from model-viewer's code base itself.

#### Live Demo
https://export-image-bug.glitch.me/
https://glitch.com/edit/#!/export-image-bug

### Version
- model-viewer: v1.2.1

### Browser Affected

- [x] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [x] Safari

### OS

- [ ] Android
- [ ] iOS
- [ ] Linux
- [x] MacOS
- [ ] Windows

**Comment by elalish** [comment]
It will generate the pixel size that it is currently rendering, which is affected by both devicePixelRatio and our dynamic render scaling. Macs tend to have DPR=2, so that's one thing to be aware of. If you're trying to grab a screenshot during active rendering, then you may want to set `minimumRenderScale=1` to disable dynamic render scale.
