### ISSUE TITLE
disable-zoom attribute is not working

### ISSUE THREAD

**Issue by aresrioja10** [google/model-viewer#1712]
### Description 

I'm trying to disable the zoom with the disable-zoom attribute but it is not working. Here is my code:

`<model-viewer
                    camera-controls
                    src="/model/table-glb.glb"
                    disable-zoom
                    camera-orbit="45deg 70deg auto"
                    field-of-view="90deg"
                    data-js-focus-visible
                    exposure="0.7"
                    min-camera-orbit="auto 50deg auto"
                    max-camera-orbit="auto 83deg auto"
                    shadow-intensity="0.4" shadow-softness="0.8"
                    environment-image="/model/hdr/lightroom.hdr"
                  />`

### Version
<script type="module" src="https://unpkg.com/@google/model-viewer/dist/model-viewer.min.js"/>
<script noModule src="https://unpkg.com/@google/model-viewer/dist/model-viewer-legacy.js"/>

**Comment by elalish** [comment]
Sorry, this was just added so it will be released in v1.4 in probably a couple of weeks. If you want to test in the meanwhile, you can set `src="https://modelviewer.dev/node_modules/@google/model-viewer/dist/model-viewer.min.js"`, since our dev pages serve off of master. Just don't use for production!

**Comment by aresrioja10** [comment]
Thank you!
