### ISSUE TITLE
Unable to place model on surface; it is floating in air

### ISSUE THREAD

**Issue by sonalmahendru** [google/model-viewer#1750]
I am using the latest model-viewer library for placing an animated santa on a surface.

However, the model is not getting placed on the surface. It is floating in air. I have tried mentioning the 'ar-placement' attribute also explicitly but that also isn't working.

Please help. Is this library version issue? Or is it something to do at model-creation level?

Code link: https://github.com/sonalmahendru/modelviewer

Code in run mode (to be checked on android): https://sonalmahendru.github.io/modelviewer/

**Comment by elalish** [comment]
It looks like your model is huge, probably exported in the wrong units. Remember that glTF specifies that all models are in meters, so you probably need a top-level transform. We have a small offset built in for shadows, so that has probably just been scaled way up. Also, our auto-target is based on the bounding box of the model at rest, so ensure that your animation doesn't transform it to some other location.

**Comment by sonalmahendru** [comment]
Thanks for your reply. I will try to fix the model and its animation then.

**Comment by vinayvidhani** [comment]
I am also facing the same issue, I have tried so many 3d models including from model viewer's as well but it always float in air. However when I tried from official page, the object placed on surface. This is my code <model-viewer src="../assets/Astronaut-Unlit.glb" alt="A 3D model of an astronaut" ar ar-modes="webxr scene-viewer quick-look" environment-image="neutral" auto-rotate camera-controls></model-viewer>

**Comment by elalish** [comment]
@vinayvidhani It's probably better to start a new discussion rather than commenting on a closed issue. Make sure to include a URL so we can repro what you're seeing.
