### ISSUE TITLE
color icons not displayed in iOS AR Mode

### ISSUE THREAD

**Issue by Arumugamhns** [google/model-viewer#1753]
I have creating a object and change the color of the object. 

That color icons are displayed in AR mode (Android chrome 86)

But not displayed in iOS chrome and safari. is there any script needed to add resolve this
![Capture](https://user-images.githubusercontent.com/60291301/101473752-39933080-3970-11eb-800e-f4859a071a7c.JPG)

**Comment by elalish** [comment]
DOM overlay and the rest of model-viewer's API is only available on the web, so for AR you need webXR mode to have these features. Since WebXR is not yet supported on iOS, we have to open Apple's QuickLook app with the USDZ or .reality file you provide in `ios-src`. Until Apple supports WebXR, we have no way to support our API in AR on iOS.
