### ISSUE TITLE
How to interact with the model

### ISSUE THREAD

**Issue by brave1126** [google/model-viewer#1759]
### Description

How to interact with the model,
I want to call a custom method when the model is clicked

**Comment by elalish** [comment]
It depends on exactly what you mean. You can add a normal eventListener to the model-viewer element; you can even get fancy enough to implement different interaction models: https://modelviewer.dev/examples/stagingandcameras/#panning

If you want to know when the user clicked the 3D object rather than the background, then you can use https://modelviewer.dev/docs/#entrydocs-annotations-methods-positionAndNormalFromPoint which will return `null` if the 3D object was not clicked.

**Comment by brave1126** [comment]
Thank you for your answer.
If there are multiple models,I want to know which model is clicked.
what should I do.

**Comment by elalish** [comment]
We only support a single model in an element at a time; do you mean separate meshes? We don't support that yet, but we plan to. If you mean separate elements, each is already independent, so standard DOM techniques still apply.

**Comment by brave1126** [comment]
thank you very much

**Comment by david-rhodes** [comment]
It's been a while since this was closed, but I was wondering if there are any updates on support for hit detection of multiple meshes inside of a single source file. 

This be used, for example, to contextually update a UI that allows the user to swap mesh-specific material settings (i.e. a configurator). 

Thank you!

**Comment by elalish** [comment]
It'll be part of an expanded scene-graph API, though that will take some time to land yet.
