### ISSUE TITLE
Scene Graph Swap Textures problem

### ISSUE THREAD

**Issue by colordrop** [google/model-viewer#2382]
### Description

I'd like to use USDZ autogenerate for my project. As far as I know, it's not released yet so I use the version from that link: https://modelviewer.dev/node_modules/@google/model-viewer/dist/model-viewer.min.js

With version 1.6.0 I was able to swap textures based on texture channel, so in my case, I change independently the base and fabric of a chair. 
Using model-viewer with auto-generate USDZ changing textures from both lists affects the whole model - I can't change the material on just one part of 3d model.

#### Live Demo
https://glitch.com/edit/#!/mire-cookie-attack?path=index.html%3A17%3A63 - model-viewer from unpkg.com
https://glitch.com/edit/#!/unexpected-fern-geology?path=index.html%3A1%3A0 - model-viewer from modelviewer.dev

### Version
https://modelviewer.dev/node_modules/@google/model-viewer/dist/model-viewer.min.js

### Browser Affected

- [X] Chrome, version: xx.x.xxxx.xx
- [X] Edge
- [ ] Firefox
- [ ] IE
- [X] Safari

### OS

- [x] Android
- [x] iOS
- [ ] Linux
- [ ] MacOS
- [X] Windows

### AR

- [x] WebXR
- [ ] SceneViewer
- [x] QuickLook

**Comment by elalish** [comment]
It seems the problem is that despite having two materials, they both point to the same baseColor texture. In fact, the legs don't appear to be textured at all, so you'd be better off with their material having just a baseColorFactor and no texture. 

Not sure why this would ever have worked before. Also, I recommend putting a link to a specific npm version rather than the latest, since I just made a release and now your two examples behave the same.
