### ISSUE TITLE
AR mode background blurry

### ISSUE THREAD

**Issue by Qiweih** [google/model-viewer#2470]
### Description

Hello, when i open AR with web XR or Scene Viewer the background is too blurry. When i take image with my camera, my camera is in high definition.

I find this topic, and it has this problem in ar core too. But it's solved by adding AutoFocus functionnality.
https://github.com/google-ar/arcore-android-sdk/issues/153

I wonder if there is a way to solve this problem using model viewer ?

Thanks

### Version
- model-viewer: v1.7.2

### Browser Affected
- [ ] Chrome

### OS
- [ ] Android

### AR
- WebXR
- SceneViewer

**Comment by elalish** [comment]
@klausw for WebXR and @tpsiaki for Scene Viewer. I've seen this feedback from several people now. Sounds like there's a new ARCore API to improve this?

@Qiweih Can you please specify the make/model of your phone and your browser version? And if you can upload a screen capture demonstrating the problem, that would help too.

**Comment by klausw** [comment]
@Qiweih - what's the distance between the camera and the background you're trying to capture? Currently, WebXR's immersive-ar mode keeps autofocus disabled to improve the experience for room scale scenarios. My understanding is that keeping autofocus enabled interferes with feature detection for distant objects, for example due to "focus breathing" where the physical focus adjustment slightly changes the camera's field of view or distortion parameters.

As you said, ARCore does have a mode to enable autofocus, but this isn't currently exposed as a selectable parameter for WebXR. The experimental image tracking mode does enable autofocus as a side effect. Could you try https://arimg.glitch.me/ after enabling "WebXR Incubations" in Chrome to see if that mode is a better fit for your use case? This obviously isn't intended as a fix, but would be a useful data point to confirm that autofocus is the issue here.

**Comment by papadako** [comment]
Hello,

can anyone comment if the autofocus feature has been disabled from image tracking? This is a show-stopper for my web XR application.

**Comment by klausw** [comment]
The current implementation turns on autofocus if there is at least one trackable image in the supplied set of images: https://source.chromium.org/chromium/chromium/src/+/main:device/vr/android/arcore/arcore_impl.cc;l=478

Please confirm with `getTrackedImageScores()` that at least one of the images you've supplied returns `trackable`.

Also, please note that this API is currently on hold due to lack of consensus in the immersive-web group, and there aren't any concrete plans for launching it at this point. This may change in the future, but please don't depend on the API for critical web applications.

We're separately investigating turning on autofocus by default for XR sessions, independent of image tracking.

**Comment by papadako** [comment]
Thank you for the reply,

Can you please check https://arimg.glitch.me/ ? At least in my POCO X3 autofocus does not work. However, the images are tracked correctly.

**Comment by papadako** [comment]
Can anyone please comment on my previous post?

Autofocus seems to be disabled for image-tracking as is shown in https://arimg.glitch.me/
