### ISSUE TITLE
multiple instances on same page: positionAndNormalFromPoint() only works on first instance

### ISSUE THREAD

**Issue by MrBushid0** [google/model-viewer#2554]
### Description

When having multiple instances of model-viewer on the same page, the method positionAndNormalFromPoint() only works on the first instance and always returns "null".

I'm building a widget out of the model-viewer and I'm trying to retrieve the position and normal coordinates on mouse click using the positionAndNormalFromPoint() method. This works fine when I only have a single instance of model-viewer on the page, but when I have several instances, Only the first instance works as expected. All the other instances always return null, whether the click hits the mesh or not. 

#### Live Demo
https://codepen.io/Souzou/pen/poPgxzX

You can see the output in the console after you click the models.

### Version
- model-viewer: v1.7.2

### Browser Affected

- [x] Chrome, version: 91.0.4472.114
- [x] Edge, version 91.0.864.59
- [x] Firefox version 89.0.2
- [ ] IE   not tested
- [ ] Safari  not tested

### OS

- [ ] Android  not tested
- [ ] iOS  not tested
- [ ] Linux  not tested
- [ ] MacOS  not tested
- [X ] Windows 10

### AR

- [ ] WebXR
- [ ] SceneViewer
- [ ] QuickLook

**Comment by elalish** [comment]
So, the problem seems to be that your `e.clientX` is relative to both MV instances (it seems to be measured from the left side of the window), so you're getting a value outside of the MV width for the clicks on the second object. I wasn't expecting `clientX` would behave that way, so I'm guessing there's something subtly wrong. MV is behaving as expected given the input though.

**Comment by MrBushid0** [comment]
Thanks for that. It looks like using `e.layerX` instead works as expected.
