### ISSUE TITLE
Internal JS error on model-viewer when auto-generating USDZ version

### ISSUE THREAD

**Issue by pedrorocha-net** [google/model-viewer#2626]
### Description

While trying to open AR mode for a Model Viewer with only GLB file specified, it's triggering an error internally on model-viewer code.

`undefined is not an object (evaluating 'material.roughnessMap.uuid')`

on the line

`if ( material.roughnessMap !== null ) textures[ material.roughnessMap.uuid ] = material.roughnessMap;`

It's on the beginning of USDZExporter class, on the first call to scene.traverse()

![image](https://user-images.githubusercontent.com/206682/127481482-f7e03377-c0db-4e89-b715-4a832ac2428b.png)

#### Live Demo
https://app.pixelar.studio/viewer/6bf66394f4c3cb75b8d84c587d311a066a51c4e0

### Version
model-viewer 1.7.2

### Browser Affected
Mobile Safari 14.1.1

### OS
iOS 14.6

### AR
- [X] WebXR

**Comment by elalish** [comment]
@mrdoob is there a reason you're checking `!== null` instead of `!= null`? That seems to be the root of the problem, though I haven't looked very deeply.

**Comment by mrdoob** [comment]
Hmm... `material.roughnessMap` shouldn't be `undefined`. It can only be `null` or a `Texture`.

The root of the problem is whatever code is making `material.roughnessMap` `undefined`?

**Comment by elalish** [comment]
Ah, so the problem is this model uses the Specular Glossiness extension, which we at glTF are doing our best to deprecate in favor of the metal-rough workflow. Your model should work just fine with regular metal-rough, and for more advanced materials we now have the specular extension to allow nearly lossless conversion.

@mrdoob `roughnessMap` is undefined because that's what GLTFLoader does for SpecGloss materials. So it feels to me like either GLTFLoader or USDZExporter has a bug around `undefined`.

**Comment by elalish** [comment]
Even if this bug is fixed, the likelihood of getting a good conversion from SpecGloss to USDZ is close to nil. I'd recommend re-exporting the model.

**Comment by elalish** [comment]
Added a console warning to help with this case:  #2628
