### ISSUE TITLE
Invisible occlusion mesh !

### ISSUE THREAD

**Issue by dthery** [google/model-viewer#2796]
Can we use the colorWrite property of three.js to create an invisible occlusion mesh that hides some areas of a model to make transparency? 
https://threejs.org/docs/#api/en/materials/Material.colorWrite

**Comment by elalish** [comment]
We don't expose that in our API since it's not part of glTF. Of course you can always fork us or hack into our internals to accomplish this, though the usual caveats apply regarding stability. If there is significant interest and use cases for it, we'd be happy to consider adding it, perhaps also to the glTF spec.
