### ISSUE TITLE
iFrame shows very pixelated model

### ISSUE THREAD

**Issue by piotrszpruta** [google/model-viewer#2822]
### Description

Model in model-viewer on iOS in iFrame is rendering very pixelated even with minimumRenderScale="1". I've checked on Xiaomi Redmi Note 7 and its looking much better.

#### Live Demo
https://d-d-ihelp.github.io/lavello-ar/

### Version
- model-viewer: v1.8.0

### Browser Affected
- [ ] Chrome, version: xx.x.xxxx.xx
- [ ] Edge
- [ ] Firefox
- [ ] IE
- [X] Safari

### OS

- [ ] Android
- [X] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Windows

### AR
- [ ] WebXR
- [ ] SceneViewer
- [ ] QuickLook

**Comment by elalish** [comment]
In fact  you did not set `minimumRenderScale` because it is not an attribute, but a static property. Please follow these directions for setting  static properties: https://modelviewer.dev/examples/loading/#dracoSupport

I've heard some concerning things about iOS throttling 3D severely in iframes. Any info you can give on relative performance between iframe and non would be helpful. I'm afraid when you set the render scale you may end up dropping frame rate significantly.
