### ISSUE TITLE
Deforming (consistent vertex) .glb animation is broken since the new release

### ISSUE THREAD

**Issue by RonenTanchum** [google/model-viewer#2986]
### Description

My .glb's NFT's were generated from blender with vertex cache 
as a deforming animated .glb and worked fine in 1.9.1,
in the newer version 1.9.2 of MV the animation looks all messed up and broken 
please see live demo on desktop

#### Live Demo
all these 3 NFTs displays with wrong animations on Desktop but still works fine on mobile:

https://foundation.app/@ronentanchum/~/90888
https://foundation.app/@ronentanchum/~/90197
https://foundation.app/@ronentanchum/~/88631

links to .glb files on IPFS:
https://ipfs.io/ipfs/QmUtuZEc12YyRiEoF7bHzH69ZraJJvXuQs9xBMxpd3Qf7C/nft.glb
https://ipfs.io/ipfs/QmS87VqXbLpPzy36rCck2AyFiJTAxwYPHx7NK16UiP1whX/nft.glb
https://ipfs.io/ipfs/QmejbvkfT8MU3yQrtgeWNoBP2jD3z51GQu4QZEbWHHHvdm/nft.glb

### Version
worked ok in 1.9.1 
1.9.2 is broken

### Browser Affected
Chrome 95.0.4638.69 

### AR
In AR these animated 3 .glb files are not moving but in the web browser they do

- [ ] WebXR
- [ ] SceneViewer
- [ ] QuickLook

**Comment by samaneh-kazemi** [comment]
Hi @RonenTanchum, thanks for reaching out. This sounds like an iOS issue. Have you tried filing a bug here?
https://bugs.webkit.org/

**Comment by samaneh-kazemi** [comment]
Hi @RonenTanchum, thanks for reaching out. I confirmed the animation doesn't work on my iPhone XR, safari, ios 15. Can you confirm if it still works with the previous version of ModelViewer like 1.8 in the same iOS/Chrome version? There is a known issue with the recent version of iOS and it'd be helpful to make sure this is not the same bug. You can also try filing a bug at https://bugs.webkit.org/ if it turns out that's the case.

**Comment by elalish** [comment]
47Mb! I'm impressed it  works as well as it does. The animation seems to be fine on Chrome on my Macbook  Pro, but I see some funny  artifacts on my Pixel 3 and it definitely doesn't work right in Scene  Viewer for AR. Did you check that  your glTFs are valid? Is this using  morph targets rather  than skeleton-based animation?

**Comment by RonenTanchum** [comment]
Hi Yes GLBs are valid, used to work fine when i minted it Sept 2021. 
Using morph targets not skeleton, something in the new ver broke this and reverting back to 1.8 fixes it on all devices.

**Comment by elalish** [comment]
@mrdoob This looks  like a three.js morph  target regression sometime in the last 6 months. Any thoughts? Sidenote: this is  why I was concerned about NFTs automatically using  the latest MV / three.js versions rather than pinning them. These  art pieces are more likely to take advantage of edge cases, and so more likely to break with no recourse when  they can't specify a version. Then again, the opposite is true for browser  bugs, so maybe this is just a hard problem...

**Comment by RonenTanchum** [comment]
Opensea did fix this, reverting back to the olderver. thanks to matt
however, in foundation its still broken and they are not reverting...

here are the links to the working version on Opensea
https://opensea.io/assets/0x3b3ee1931dc30c1957379fac9aba94d1c48a5405/90888
https://opensea.io/assets/0x3b3ee1931dc30c1957379fac9aba94d1c48a5405/90197
https://opensea.io/assets/0x3b3ee1931dc30c1957379fac9aba94d1c48a5405/88631

**Comment by mrdoob** [comment]
I'm unable to reproduce. The animation looks identical in OpenSea and Foundation here (Chrome 97, MacOS 11.6.2).

For people that can reproduce the issue, any chance that you can share a screen recording here?

**Comment by elalish** [comment]
Yeah, it's fine on my macbook too. My Pixel 3 was showing some issues though. I'd  guess Windows? @RonenTanchum Can you be very specific about what devices repro the behavior and share a screen recording?

**Comment by RonenTanchum** [comment]
Yes, on mac+chrome looks ok, but on PC(win10)+chrome is broken on foundation please see screen recordings
https://user-images.githubusercontent.com/19776099/148841430-018844bd-7ffd-486e-9bf8-7f47484d2b3e.mp4

**Comment by mrdoob** [comment]
Thanks @RonenTanchum 🙏

@samaneh-kazemi you said:

> I confirmed the animation doesn't work on my iPhone XR, safari, ios 15.

Do you mind specifying that "doesn't work" mean? Do you mean that it doesn't play, or that it looks like in the screen recording @RonenTanchum shared?

**Comment by mrdoob** [comment]
@samaneh-kazemi you said:

> I confirmed the animation doesn't work on my iPhone XR, safari, ios 15.

Do you mind specifying that "doesn't work" mean? Do you mean that it doesn't play, or that it looks like in the screen recording @RonenTanchum shared?

**Comment by RonenTanchum** [comment]
I tested on 2080ti rtx & on 980ti gtx 
win10 with nvidia drivers 457.30

**Comment by mrdoob** [comment]
Thanks!

Okay, I suspect https://github.com/mrdoob/three.js/pull/22293 is the culprit.

**Comment by Mugen87** [comment]
Yeah, the new morph target implementation based on texture arrays seems to be problematic on certain devices. Unfortunately, I have no device at hand that reproduces the bug but some devs at the `three.js` repo reported related issues:

https://github.com/mrdoob/three.js/issues/23190
https://github.com/mrdoob/three.js/issues/23063

@RonenTanchum Can you please verify if the same issue occurs if you import the asset with BabylonJS? 

https://sandbox.babylonjs.com/

The morph target implementations are similar since both engines use texture arrays for organizing morph data. If it works with BabylonJS, there is a good chance to fix something in `three`'s shaders.

**Comment by Mugen87** [comment]
This issue should be fixed in `three.js` starting from `r139`.

**Comment by RonenTanchum** [comment]
Hell yeah! thanks so much for the update, this means a lot finally people
would get to enjoy those glbs :)

Working on some new cool ones\!

Thanks,
Ronen
__________
*RONEN TANCHUM*

*CREATIVE DIRECTOR | FOUNDER+972-585477962 | +17788075118*
*PHENOMENALABS.COM <http://phenomenalabs.com/>*

**Comment by elalish** [comment]
Fixed in #3350
