### ISSUE TITLE
Camera jitter with small orbit distances

### ISSUE THREAD

**Issue by hybridherbst** [google/model-viewer#3012]
### Description

If models are intended to be used with AR and have annotations, they need to be pretty small (<1m).
When they're detailed one also needs to use small orbit values (e.g. 1% or 0.01m).
I suspect there's a rounding error somewhere since at such small values there's a lot of jitter when moving the camera around (e.g. panning).

#### Live Demo
https://glitch.com/edit/#!/thor-and-the-serpent?path=index.html%3A52%3A37

It's obvious in the live demo but also visible here as "jumps" (whenever the camera gets close to its rest position?):
![ezgif com-gif-maker](https://user-images.githubusercontent.com/2693840/144472481-f4b1d1f2-a174-4452-80c8-6154779334e7.gif)

### Version
- model-viewer: v1.9.2

### Browser Tested
- [X] Chrome
- [X] Edge
- [ ] Firefox
- [ ] IE
- [X] Safari

### OS Tested
- [X] Android
- [X] iOS
- [ ] Linux
- [ ] MacOS
- [X] Windows

**Comment by elalish** [comment]
I'm 99% sure that's caused by this line of code: https://github.com/google/model-viewer/blob/master/packages/model-viewer/src/three-components/Damper.ts#L47

It's there to bring the movement to a halt, since otherwise it would asymptote out forever. I  thought  I had normalized it properly, but you seem to have found a case where I'm doing it wrong. Suggestions welcome!
