### ISSUE TITLE
UX: click-to-zoom is confusing and has interaction overlap

### ISSUE THREAD

**Issue by hybridherbst** [google/model-viewer#3334]
### Description

`enable-pan` brings a new behaviour with it: clicking on a point does multiple actions at the same time.
- sets the center of view
- zooms in

To me this is very confusing, and I find myself zooming out all the time because I effectively can't navigate around a model.
What was the reasoning for including zoom in the same gesture? Especially since zooming out requires mouse wheel or two fingers anyways (the context isn't always reachable), I'd expect zooming in to behave the same (require mouse wheel or two fingers).

I'd even want center of view to be on double-click / double-tap to prevent misclicks, but that might be personal preference.

### Version
- model-viewer: v1.11.0

**Comment by elalish** [comment]
The reasoning was that clicking outside of the model zooms out fully, so there's some symmetry to zooming in. Also, we found in user testing that people didn't notice tap was doing anything, because often the shift was too small to be very noticeable. Likewise, we considered the purpose of "tap to center" being to inspect a particular feature, which would therefore nearly always be followed by zoom. 

Most of this is about discoverability, as we're targeting first and foremost lay users who are not familiar with 3D navigation. Using single tap instead of double tap, and having it cause both pan and zoom helps users discover that both of these are possible, and ideally leads them to try multi-touch as well. 

Are you getting accidental taps? It could also be that our drag threshold needs to be adjusted.

**Comment by hybridherbst** [comment]
Hm, I can't quite follow that reasoning. Are you saying discoverability is proritized over usability here, at the expensive of introducing an interaction assymetry? 
Context click doesn't zoom out once but fully as far as I can see; once you're zoomed in a bit focus changes are very visible.

I'm regularly getting "lost" in models now since that zoom is _never_ what I want:
https://user-images.githubusercontent.com/2693840/161168652-9eceb9a4-0612-48f8-af09-0871fe46267a.mp4

I can immediately see a lot of clients asking me why they're getting closer and closer to the model when they just click on it... that's doesn't help discoverability in my opinion, it just teaches people they need to be careful to not click on the model at all since that will do unexpected things.

**Comment by elalish** [comment]
Thanks for the feedback! Why do you click on the model? Honestly, watching your video, that is what I would expect to happen (closely inspect the feature I clicked on). But you clearly have a different idea in mind; what user journey do you envision? It also looks like you've set the zoom to go in quite a bit further than default. 

To me, having taps zoom both in and out is more symmetric than some taps zooming and some not, but that's just how I look at it. I also think it's more usable to be able to zoom without using two fingers. Is the problem that users might get stuck zoomed in and not know how to return to the full view? I am concerned about this; perhaps double-tap as a backup for tap-outside of model in case the background is not visible?

**Comment by hybridherbst** [comment]
I click on the model because that is something we see from users a lot: people click on something that they look at. Expectations vary; from "part should be highlighted" to "nothing, just pointing" to "wanted to move over there", I haven't heard that someone expected any kind of zooming in but I think I understand the angle you're coming from.

For me "symmetric" would mean I can do undo the action as quickly as I can do it; that is the case for mousewheel and two-finger zoom, but that's not the case for undoing a zoom in with a potentially not even available background click (know that background has interactivity, find free area of background, move finger over there, double-tap). Double-tapping is also not something I would expect undoing a single tap.

Another assymetry here is "Tap on interesting point 1, tap on interesting point 2, tap on interesting point 1 again" - the expectation would be that the result is the same, but currently I'd just zoom in more and more.

The user journey is simply "move around a model and inspect it": 
https://user-images.githubusercontent.com/2693840/161170639-8292b995-d0ae-434e-8234-24c7d31629fa.mp4

Here's something closer to my expectations (custom panning implementation based on the previous example)
https://user-images.githubusercontent.com/2693840/161170681-f45bb96c-8dc8-46bd-8ceb-2eed343130ab.mp4

**Comment by hybridherbst** [comment]
Side note here: is the little "center" marker intended? At first I thought it was a bug, or that somehow Windows decided to show me a stuck touch pointer, but seems it marks where the pivot will be?

![image](https://user-images.githubusercontent.com/2693840/161170970-ee8b444f-ae3d-4dca-88f4-86cbcc86a939.png)

**Comment by elalish** [comment]
Fair points, you're convincing me. I want to run it past some others too, but it's an easy change. Zoom out is single-tap on background; the idea was to add double-tap anywhere for the same action. 

Yes, the center point is there to show you your focus point when panning. I found myself having trouble centering what I cared about when panning with two fingers. Anyway, it's a slot (`pan-target`), so you can easily disable it if it bothers you. It should only be visible while you pan; if you see it otherwise, it's a bug. Is it bothering you?
