### ISSUE TITLE
The editor doesn't export/download the scene after adding variants to the model.

### ISSUE THREAD

**Issue by elalish** [google/model-viewer#3814]
### Discussed in https://github.com/google/model-viewer/discussions/3746

<div type='discussions-op-text'>

<sup>Originally posted by **plutorkhan** May  4, 2022</sup>
I want to apply different texture variants to a hottub 3d model via model-viewer editor. I could import and add textures per variant, but couldn't download the scene. I've tested other glb 3d models the same bug happens again.
The console logs:

 (in promise) TypeError: Cannot read properties of undefined (reading 'material')
    at space-opera.js:88772:60
    at Mesh.traverse (space-opera.js:33845:3)
    at Group.traverse (space-opera.js:33851:18)
    at GLTFExporterMaterialsVariantsExtension.beforeParse (space-opera.js:88763:20)
    at space-opera.js:88132:27
    at GLTFWriter._invokeAll (space-opera.js:88178:4)
    at GLTFWriter.processInput (space-opera.js:88130:8)
    at GLTFWriter.write (space-opera.js:86499:8)
    at GLTFExporter.parse (space-opera.js:86187:10)
    at space-opera.js:90230:26

I used chrome and edge, the results are the same.

</div>

**Comment by Readerr57** [comment]
New info.

This file works and can be exported normally from Model Editor: https://modelviewer.dev/shared-assets/models/glTF-Sample-Models/2.0/MaterialsVariantsShoe/glTF-Binary/MaterialsVariantsShoe.glb

But, as soon as I add one more variant, I can`t export it anymore. Only original file can be exported, but not after added variants.

**Comment by Readerr57** [comment]
I tested different things and narrowed the problem and I am quite a sure that I have found the root cause.

If I leave material variant untouched, I can`t download file. But if I edit each variant, downloading is possible.

This is how you can test this:

**Can`t dowload the model**
1. Use this model: https://modelviewer.dev/shared-assets/models/glTF-Sample-Models/2.0/MaterialsVariantsShoe/glTF-Binary/MaterialsVariantsShoe.glb
2. Create new variant.
3. Click "Download scene" button. Nothing happens.

**Can download the model**
1. Use this model: https://modelviewer.dev/shared-assets/models/glTF-Sample-Models/2.0/MaterialsVariantsShoe/glTF-Binary/MaterialsVariantsShoe.glb
2. Create new variant.
3. Click Base Color texture slot and choose same texture as model has already.
4. You can notice that viewer adds variant name after selected material name.
5. Click "Download scene" button. Now it works.

Key is to edit each material variant so that variant name appears after material name. This seems to fix all downloading problems.

**Comment by elalish** [comment]
Thank you for the details! This will make it quite a bit quicker to solve this issue.
