### ISSUE TITLE
Asset is downloading on pressing sharing button in chrome(ios).

### ISSUE THREAD

**Issue by pnkj1002** [google/model-viewer#4222]
### Description
When I press share button in quick view mode it download asset instead of sharing link in chrome. In safari it is working fine.

### Version
- model-viewer: v3.0.2

### Browser Affected
- [-] Chrome

### OS
- [-] iOS

### AR
- [-] QuickLook

**Comment by elalish** [comment]
What version of iOS and Chrome? We had this bug some time ago, but it was fixed. Can you check if updating helps?

**Comment by pnkj1002** [comment]
@elalish
- iOS -  16.4.1
- Chrome - 112.0.5615.46

**Comment by pnkj1002** [comment]
Also can you explain how  I override default functionality of share button

**Comment by elalish** [comment]
Oh, I think I misread this before - so Quick Look is opening properly, but you click its share button the wrong thing happens? That sounds like a Chrome bug - would you mind filing that on Chromium?

There isn't any way to customize Quick Look beyond a couple of URL parameters, since it's an app and not in the web.
