### ISSUE TITLE
Configurable animation iteration count

### ISSUE THREAD

**Issue by cdata** [google/model-viewer#424]
As of #421 , we support playback of animations in models. The default behavior for this feature is to play a selected animation continuously. However, we may want to support user-configurable iteration count to limit the number of times an animation is looped. The default would remain what it is as of #421: infinity.

**Comment by donmccurdy** [comment]
Perhaps worth considering this as a 'mode' rather than an integer property. For example, see [`THREE.AnimationAction.loopMode`](https://threejs.org/docs/#api/en/animation/AnimationAction.loop)'s three states:

- THREE.LoopOnce - playing the clip once,
- THREE.LoopRepeat - playing the clip with the choosen number of repetitions, each time jumping from the end of the clip directly to its beginning,
- THREE.LoopPingPong - playing the clip with the choosen number of repetitions, alternately playing forward and backward. 

Ping-pong could be helpful for something like a door opening, where the animation should be played in reverse before restarting.

**Comment by elalish** [comment]
We have this now: https://modelviewer.dev/docs/#entrydocs-animation-methods-play
