### ISSUE TITLE
model viewer js in unpkg not running location animation correctly!

### ISSUE THREAD

**Issue by LazZiya** [google/model-viewer#4419]
### Description

The model viewer file provided at [unpkg ](https://unpkg.com/@google/model-viewer@3.2.0/dist/model-viewer.min.js)is not playing the location animation properly!
https://unpkg.com/@google/model-viewer@3.2.0/dist/model-viewer.min.js

The same version provided in [google apis](https://ajax.googleapis.com/ajax/libs/model-viewer/3.2.0/model-viewer.min.js) is working correctly!
https://ajax.googleapis.com/ajax/libs/model-viewer/3.2.0/model-viewer.min.js

#### Live Demo
In this demo the red cube must go forward  and backward through the blue one.

The first sample is using unpkg library and it is not playing location animation correctly:
https://demo.ziyad.info/webar-models/anim-bug/index-b.html

The second sample based on the same model but using googleapis is working fine:
https://demo.ziyad.info/webar-models/anim-bug/index-a.html

### Version
- model-viewer: v3.2.0

### Browser Affected

- [x] Chrome
- [x] Edge

### OS

- [x] Android
- [x] iOS
- [x] Windows

**Comment by elalish** [comment]
Okay, so good news is this helped us identify and fix a google apis issue, which is that we managed to point the 3.2.0 version back at 3.1.1, hence the discrepancy with unpkg. We've updated that, so hopefully it will serve the proper version in a day or so. 

The bad news is, what you're describing is a three.js regression, so now it will be broken in both places instead of one. I'm hoping it's already been [fixed](https://github.com/mrdoob/three.js/pull/26477), so we'll get it with our next update to r155. Meanwhile, you'll probably want to pin to 3.1.1.
