### ISSUE TITLE
User-configurable screen reader view angle announcements

### ISSUE THREAD

**Issue by cdata** [google/model-viewer#442]
In #325 , we introduced camera orientation announcements for screen readers.

It would be nice if users could somehow customize / configure the a11y strings used when the camera is viewing at various angles.

**Comment by svinkle** [comment]
To add to this, this feature would be very handy in an online store setting as accurately describing a product is crucial for the buyer experience.

Take for example, a baseball hat. The model would start in its default, front facing position. The model would be announced describing its features, including color and perhaps a logo on the front. The user, using the keyboard arrow keys, turns the model 180 degrees to view the back. The description now informs the potential buyer that the hat features a strap for sizing fit. They were hoping for a full-back and decide to move on.

This has created the _equal experience_ accessibility advocates strive to achieve for users of assistive technology. Please take this into consideration. 🙂

**Comment by elalish** [comment]
I think this is out of scope, as getting users to supply decent alt text is hard enough.

**Comment by svinkle** [comment]
@elalish Getting authors to supply appropriate `alt` is difficult. But providing an API within `model-viewer` to allow other apps to serve author `alt` is in scope. Otherwise, interacting with a 3D model could be perceived as a multi-sided image with inaccurate or missing `alt` text.

More details: https://github.com/Shopify/dawn/issues/869
