### ISSUE TITLE
Separate instruction element

### ISSUE THREAD

**Issue by svinkle** [google/model-viewer#462]
### Description

Currently, the instructions on how to interact with the 3D model (_"Use mouse, touch or arrow keys to control the camera!"_) are announced after a short time via updating the `aria-label` of the canvas element.

With the changes suggested in #461, it will be required to set aside the instructions and include with the focus announcement in a different manner.

**Recommendation:** Set the instructions in a new, `hidden` element. Include the instructions on the `canvas` element via `aria-describedby` attribute, referencing the `id` of the instructions container. This will help to announce the 3D model with its `aria-label`, and then, the instructions will follow.

```html
<span id="instructions" hidden>
  Use mouse, touch or arrow keys to control the camera!
</span>
<!-- … -->
<canvas … aria-describedby="instructions">
  <!-- … -->
</canvas>
```

### Browser Affected

- [ ] Chrome
- [x] Edge
- [x] Firefox
- [ ] Helios
- [x] IE
- [ ] Safari

### OS

- [x] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [x] Windows

### Versions

- model-viewer: v0.1.1

**Comment by cdata** [comment]
Thanks! This seems like something we could consider. I don't understand why #461 would _require_ that the instructions be static. Could you clarify what you mean by that?

**Comment by svinkle** [comment]
Oh, I mean if we go through with #461 (and #460), we'll need to also make this change here, since these instructions are currently announced via `aria-label` + `aria-live` attributes.

These three tickets are all connected; perhaps it should have been one ticket. 🤔

**Comment by PeterSaathoff-Harshfield** [comment]
I agree that the keyboard instructions should not be dynamically announced via aria-live, since they aren't time-sensitive and/or were not triggered by a user action.

However, I don't think it makes sense for these instructions to be readable only by screen reader users. Non-screen reader users who use only the keyboard to navigate benefit from these instructions just as much as screen reader users do. So, they should be available to all keyboard-only users, not just screen reader users. Would it be possible to show this text when some part of the viewer receives keyboard focus?

**Comment by elalish** [comment]
Thanks @PeterSaathoff-Harshfield! I'm trying to find something similar to us to use as inspiration so we don't have to blaze a completely new trail as we figure out how to make 3D accessible. My best idea so far is a Google Maps embed (effectively another visual web component with rich user interactions). Sadly it sounds like people aren't terribly happy with the job they did either: https://stackoverflow.com/questions/62530864/google-maps-and-accessbillity

Can anyone think of any other examples we could look to?
