### ISSUE TITLE
Progress bar completes before the .glb file had finished downloading

### ISSUE THREAD

**Issue by grigs** [google/model-viewer#4653]
### Description

This issue is reproducible when you throttle your connection to Fast 3G or lower. The progress bar completes before the .glb file has completed downloading which makes it seem like nothing is happening.

The behavior exists when loading="lazy" is set. If loading="eager" is set, the progress bar works as expected. 

My theory is that the progress bar completes when the poster image finishes downloading when lazy is turned on. 

#### Live Demo
I recorded a short video demonstrating the behavior:
https://www.loom.com/share/6c41ddea47ab43a29924d3c87c7f9d9b?sid=85bc7dc0-4d6f-4b0a-a2fa-6b021533198c

The CodePen I used in the video is here:
https://codepen.io/grigs/pen/WNmrogN

But I don't think there is anything special about the CodePen and you really can't reliably see the behavior it unless you throttle your connection and watch what happens in the network panel. The size of the model, the size of the poster image, and the speed of your network likely make observing this behavior difficult without throttling.

### Version
- model-viewer: v3.3.0

### Browser Affected
- [x] Chrome, version:  120.0.6099.234
- [x] Edge 120.0.2210.144
- [x] Firefox 121.0
- [ ] IE
- [x] Safari 17.1 — I couldn't figure out how to throttle my network here so I'm fairly certain the behavior is the same, but it went much more quickly than in other browsers.

### OS
- [ ] Android
- [x] iOS 17.2.1
- [ ] Linux
- [x] MacOS 14.1.1
- [ ] Windows

_Originally posted by @grigs in https://github.com/google/model-viewer/discussions/2202#discussioncomment-8008198_

**Comment by elalish** [comment]
Thanks, I would guess that your theory is correct. Unfortunately your video doesn't seem to have any audio? Interested in trying a PR?

**Comment by elalish** [comment]
Nevermind, we already got that from your PR. But good for future reference.

**Comment by elalish** [comment]
Okay, I finally took a closer look at this. Basically the problem is you're listening to the first set of progress events and ignoring any after that, and in some cases the poster loads completely before the model starts to download, hence you get two separate sets. I think it's fairly simple to tweak the custom progress code to handle this (our default progress bar does not repro this issue). Also, I think #4701 fixed the propagation of an even reason, which you could also use to decide whether to update or not. So, I'm going to mark this as fixed.
