### ISSUE TITLE
Support KHR_lights_punctual extension

### ISSUE THREAD

**Issue by ochafik** [google/model-viewer#4832]
### Description

Context: as part of making the [OpenSCAD Web Playground](https://ochafik.com/openscad2)'s output look the same as the Desktop version of OpenSCAD, I've exported the default OpenSCAD lights into glTF under the [KHR_lights_punctual](https://github.com/KhronosGroup/glTF/blob/main/extensions/2.0/Khronos/KHR_lights_punctual/README.md) extension. 

It doesn't seem to be supported by model-viewer yet (but it is by [babylon.js](https://sandbox.babylonjs.com/), for instance).

As a workaround I've created a very crude `environment-image`, but I'm struggling to make it match the lights I want.

Could you please consider adding support for that reasonably-standard extension?

#### Live Demo

To repro: remove the `environment-image` from the `<model-viewer>` tag in the View tab of https://ochafik.com/openscad2

(example file [lights.glb.zip](https://github.com/user-attachments/files/16121434/lights.glb.zip) - had to zip it to attach here)

<img width="366" alt="image" src="https://github.com/google/model-viewer/assets/273860/6b66eeac-ace7-43fb-81a7-b9617aa96f92">

Same file in babylon.js:

<img width="403" alt="image" src="https://github.com/google/model-viewer/assets/273860/38a3ff0c-08f2-4a34-8b6e-57e37dde5cef">

**Comment by elalish** [comment]
We do support KHR_lights_punctual, and I'm not sure what about your two images makes it seem like we don't. We do apply a default environment image when none is supplied - perhaps that is the problem? You could always supply a small black image to turn that off. However, I'd highly recommend rendering your lights into an environment image instead, which is usually pretty simple with a cube camera. 

Also, just saying as an OpenSCAD user - its lighting is not great. Maybe a good excuse to improve it?

**Comment by ochafik** [comment]
While I'm at it, two more questions:
- Would it be possible to have lights that move with the camera?
- How small can the black environment map be? (just tried w/ 1x1px and it seemingly ignored it)

**Comment by elalish** [comment]
>Would it be possible to have lights that move with the camera?

Not very easily - we intentionally don't do our lights this way, as it reduces the information the lights give you about shape. Honestly, we worked pretty hard on our default lighting in MV - it's one of the things I like best about using ManifoldCAD.org over OpenSCAD. You might consider adopting it, or something like it. 

>How small can the black environment map be? (just tried w/ 1x1px and it seemingly ignored it)

Good question - I would have thought 1x1 would work, but there may be some small bug. 64x32 should certainly be fine. Let me know if you find anything weird. 

>do you use any existing tools to render your own maps?

Usually Three.js. Though you can only render emissive objects, rather than actual lights, so it might not help you much. A Directional light is just a single, very bright HDR pixel.
