### ISSUE TITLE
Ability to auto-orbit the camera a la auto-rotate

### ISSUE THREAD

**Issue by hybridherbst** [google/model-viewer#576]
### Description

When using both auto-rotate and background-image, the image clearly doesn't rotate while the model does. This looks and feels very weird, especially given that when using the mouse to rotate it looks right.

I found some information about it in https://github.com/GoogleWebComponents/model-viewer/issues/459 where it is stated that auto-rotate rotates the model while controls rotate the camera. While I understand that this makes it a lot easier to develop, this is not what a user would expect. It feels wrong, and like a bug.

#### Live Demo
https://glitch.com/~grove-koi

### Browser Affected
All

### OS
All

**Comment by cdata** [comment]
`auto-rotate` currently applies to a virtual turntable node that the model is placed on. This means that the model rotates independently from the rest of the scene. If `auto-rotate` applied to the camera instead, then the background would rotate as you expect, but right now we deliberately do not do that.

We may want to investigate adding configuration to this so that the user can specify `auto-rotate` via turntable or camera as desired.

**Comment by cdata** [comment]
Upgrading this to a feature, as we have received requests from other users for the same.

In the mean time, take note of the work-around suggested in https://github.com/GoogleWebComponents/model-viewer/issues/911#issuecomment-560473335

**Comment by elalish** [comment]
We now have an example showing how to do this with a bit of JS.
