### ISSUE TITLE
Where to report models that look right in model-viewer but break in SceneViewer?

### ISSUE THREAD

**Issue by hybridherbst** [google/model-viewer#811]
### Description
I have some glb files that render correctly everywhere (model-viewer, babylon, donmccurdy's viewer, Sketchfab) but render incorrect in SceneViewer. What's the right place to report this to get it fixed?
@cdata you were of great help with forwarding that in the past – is the "right interim place" still opening issues here and you forward them?

**EDIT:** maybe I'm answering my own question after a bit more searching - would that be https://github.com/google/filament?

#### Live Demo
Confidential; I can share a link right now via email and will ask whether I can share it publicly soon.

### Browser Affected

- [X] Chrome

### OS

- [X] Android

### Versions
model-viewer is fine, SceneViewer bug

**Comment by cdata** [comment]
@soraryu unfortunately there is no good public forum for reporting bugs directly to the Scene Viewer team at this time. If you can reproduce the bug in Filament's own `gltf_viewer`, then you can report the bug to Filament. In general it is better to assume that a Scene Viewer bug is not the same as a Filament bug, so test Filament directly!

That said, as long as there aren't too many bugs to deal with we are happy to forward bugs to the Scene Viewer team.

Could you share screenshots of the bug, or even better: the model? (I know this may not be possible, but it will help a lot with filing the bug internally)

**Comment by cdata** [comment]
@soraryu after syncing with the Scene Viewer team on this, they also suggested that you try out the model in this beta previewer tool that they are working on: https://vr.google.com/scene-viewer-preview

The tool has a console on the bottom that will alert you to any obvious problems with the model that you can fix on your own.

**Comment by soraryu** [comment]
Oh wow, thanks for sharing that beta preview tool, that's super helpful for testing stuff before going on device.
The issue is present there as well. Do you have an email address that I can share the model and pictures to?

Maybe it's helpful, another issue I found on that tool, with another model - shadow distance is too short:
![20191010-210914_chrome](https://user-images.githubusercontent.com/2693840/66598977-8e87bb00-eba2-11e9-8a77-5d2d16239add.png)
[comp-20190923-174143.zip](https://github.com/GoogleWebComponents/model-viewer/files/3714222/comp-20190923-174143.zip)
(shadows work fine on that model when running on Scene Viewer on Android in AR mode).

**Comment by cdata** [comment]
@soraryu You can use my Github user name at my company name dot com if you want to share those things with me directly. Please only use it for bug reports that cannot be posted to Github, though!

**Comment by soraryu** [comment]
OK, sent you a mail! Hope I decrypted the mail address right.

**Comment by cdata** [comment]
Got it, thanks!

**Comment by cdata** [comment]
The issue has been filed with the Scene Viewer team. I'll update here when I see activity on it.
