### ISSUE TITLE
Publish a minified version of the bundled build

### ISSUE THREAD

**Issue by soraryu** [google/model-viewer#819]
### Description
model-viewer currently doesn't have minified releases online (or does it?).
Would be great if it follows the same pattern as other production libraries and just allows to turn "model-viewer.js" into "model-viewer.min.js" on the unpkg url.
(minifying it with online tools goes from 1.4MB to 0.7MB)

#### Live Demo
https://unpkg.com/@google/model-viewer/dist/
for comparison, three.js
https://cdnjs.com/libraries/three.js/

### Versions

- model-viewer: v0.6.2

**Comment by cdata** [comment]
@soraryu yes, I agree, we should minify the bundle.

In the long-run, I hope that we can find ways to make it easier for folks to consume the library via NPM, or at least load the unbundled version from unpkg.com.

The bundle is very large because it contains Three.js, and some folks who want to use `<model-viewer>` will also load Three.js separately on the page. This will result in a lot of avoidable JavaScript bloat. The theoretical way to do better is to ask users to bundle the library themselves as part of a build pipeline that includes minification, but in order to do that they must first depend on an unbundled build.

All that to say, we are offering the bundled build as a convenience, because it is easy for people to use. But, for production scenarios, folks should not be using it if they want to get the best performance.

**Comment by soraryu** [comment]
I have to admit, I'm not very versed in the web world. Could you give a high-level overview over what it would take to bundle model-viewer myself with a version of three.js that I'd want to load separately? Or do you have a good link to check?

**Comment by cdata** [comment]
There are several tools that folks use in the web world, but every solution tends to be somewhat unique. I admit, it's not an easy topic to explain, or an easy one to break into for outsiders.

For starters, there are tools in Web/JS land that we colloquially call "bundlers," which users configure for their specific app or use case. The bundlers read in JavaScript (or other languages, depending on the bundler and its configuration), analyze all of the dependency relationships between every file, and produce optimized JavaScript output files. In simple cases, bundlers produce one big, concatenated, minified output file for a given input. In more sophisticated cases, bundlers are able to analyze the dependencies needed on each page in an app, and produce different output bundles and also a common bundle so that every page only loads as much as it needs. Some bundlers even produce different outputs for different browsers.

Some popular bundlers include:

 - https://webpack.js.org/ ([Getting started](https://webpack.js.org/guides/getting-started/))
 - https://rollupjs.org/guide/en/ ([Creating your first bundle](https://rollupjs.org/guide/en/#creating-your-first-bundle))
 - https://parceljs.org ([Getting started](https://parceljs.org/getting_started.html))

Almost all bundlers that I'm aware of assume that the user has a working knowledge of Node.js and NPM, and that they are installing their packages using NPM.

So, to bundle on your own, you would have to do something like this:

 1. `npm install <your bundler>`
 2. `npm install @google/model-viewer`
 3. `npm install three`
 4. Configure the bundler per its documentation (this is usually the hardest part)
 5. Build your app
 6. Run the bundler to produce optimized production artifacts

If you clone the `<model-viewer>` repository and follow our readme to get setup for development, you will be able to see how we bundle using Rollup as an example.

And if all that sounds like a lot, that's why we offer bundled builds: 'cause it's a lot 😓

**Comment by soraryu** [comment]
Many thanks for the detailed write-up!

**Comment by elalish** [comment]
@cdata You've now written a bunch of these really helpful comments for people that I would hate to see go to waste in a closed issue. I'm wondering if we should create an FAQ document somewhere that either copies or links to these generally useful ones so people can find them more easily. Does that sound like a good idea to you?

**Comment by soraryu** [comment]
Has it ended up in a FAQ as @elalish had suggested? :)

**Comment by elalish** [comment]
@hybridherbst No, we've decided to rely on Github's search capabilities for now to find these. But the official minified build will be published shortly!
