### ISSUE TITLE
Progress bar styles can get overridden by external CSS in IE

### ISSUE THREAD

**Issue by pushmatrix** [google/model-viewer#840]
### Description

IE11 doesn't support the shadowdom, so it just places the divs in the same DOM as everything else. The progress bar has class `progress-bar`, which can conflict with styles from other css. In particular, Bootstrap has a `progress-bar` style.

So now the progress bar style is all messed up in IE, covering up the whole model-viewer:
<img width="296" alt="Capture3" src="https://user-images.githubusercontent.com/190692/67058633-a1ab0580-f123-11e9-840e-186ba64e3f90.PNG">

#### Live Demo
Visit this in IE11: https://pushmatrix.github.io/temp/bootstrap

### Browser Affected

- [ ] Chrome
- [ ] Edge
- [ ] Firefox
- [ ] Helios
- [x] IE
- [ ] Safari

### OS

- [ ] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [x] Windows

### Versions
- model-viewer: v0.7
- three.js: r108

**Comment by cdata** [comment]
@pushmatrix I see in your repro case that you are not loading the Web Components polyfills, which are required for IE11 support, and which also enable limited encapsulation via ShadyCSS. Is there a reason why you did not include the polyfills?

**Comment by cdata** [comment]
Please refer to this document for additional details regarding our polyfill requirements: https://github.com/GoogleWebComponents/model-viewer/blob/master/POLYFILLS.md

**Comment by cdata** [comment]
For additional details on the limitations of ShadyCSS scoping, please refer to this subheading of the ShadyCSS README.md: https://github.com/webcomponents/polyfills/tree/master/packages/shadycss#document-level-styling-is-not-scoped-by-default

In order to guarantee that a top-level stylesheet _does not_ influence the `<model-viewer>` DOM, you must wrap it in a <custom-style> element like the one defined in this example:  https://github.com/webcomponents/polyfills/blob/master/packages/shadycss/examples/custom-style-element.js

**Comment by pushmatrix** [comment]
@cdata This is our own custom bundle of model-viewer-legacy which has all the polyfills inside of it.

**Comment by cdata** [comment]
@pushmatrix nevertheless, you must coordinate with the ShadyCSS polyfill in order to ensure correct encapsulation from document-level styles. You don't have to follow the `<custom-style>` pattern exactly, but top-level stylesheets must have the ShadyCSS polyfill applied to them *somehow*, or else document-level styles have a fair chance of intruding on `<model-viewer>`'s local styles.

**Comment by cdata** [comment]
I'll put together an example for you tomorrow.

**Comment by cdata** [comment]
Here is a demo of one way that document-level styles can be scoped with ShadyCSS: http://lopsided-motion.glitch.me/shadycss-scoped-styles.html

Not scoped | Scoped
------------|---------
![image](https://user-images.githubusercontent.com/240083/67114185-30ee0280-f190-11e9-8969-f37a683a8aaa.png) | ![image](https://user-images.githubusercontent.com/240083/67114223-4e22d100-f190-11e9-835b-f4fc50a7d45b.png)

Note that the important details in this demo include:

 - In IE11 only, the helper script containing `CustomStyleInterface` is loaded
 - Somehow the top-level `<style>` elements that should be scoped are selected
 - All selected styles have `CustomStyleInterface.addCustomStyle(styleElement)` invoked on them

There are variations of this in use, and notably our team has historically wrapped `<style>` elements in a `<custom-style>` element wrapper that is only defined when needed (e.g., in IE11), and applies the `CustomStyleInterface` implementation automatically once upgraded.

**Comment by pushmatrix** [comment]
Ah interesting, that wasn't clear at first. Thanks for providing this example.

So this is the same that would have to be done for external css being included, like bootstrap?

**Comment by elalish** [comment]
IE is no longer supported.
