### ISSUE TITLE
Cant run model-viewer with WIX

### ISSUE THREAD

**Issue by IvanNov7** [google/model-viewer#983]
Hello every one, i try to add the model viewer script to my wix site and some why it doesnt work.
Here the code i add to head:
```
<script type="module" src="https://unpkg.com/@google/model-viewer/dist/model-viewer.js"></script>
<script nomodule src="https://unpkg.com/@google/model-viewer/dist/model-viewer-legacy.js"></script>
```

And then i add this to HTML iframe module:
`<model-viewer src="shared-assets/models/Astronaut.glb" alt="A 3D model of an astronaut" auto-rotate camera-controls background-color="#455A64"></model-viewer>`
That works perfect on regular website but not on wix...
Anyone can help me ?

**Comment by cdata** [comment]
@IvanNov7 it should work fine, but I'm not a wix expert.

Can you share a link to the wix site you are trying to use it on? I might be able to see what is going on with a live demo, but without it I would just be speculating about the problem.

**Comment by IvanNov7** [comment]
@cdata 
Thank you for your replay.
I tryed the demo code and works fine but when i try to test any other model, its not works even in code testing sites.
Here example :
```
<script type="module" src="https://unpkg.com/@google/model-viewer/dist/model-viewer.js"></script>
<script nomodule src="https://unpkg.com/@google/model-viewer/dist/model-viewer-legacy.js"></script>

<model-viewer src="https://In3dReal.net/Olin_Yam.gltf" alt="A 3D model of an astronaut" auto-rotate camera-controls background-color="#455A64"></model-viewer>
```

**Comment by cdata** [comment]
@IvanNov7 I tried loading that model using the same URL you are using. It looks like the domain (`In3dReal.net`) is not setting permissive CORS headers in the network response. This is causing network requests for the model to fail.

Although `<model-viewer>` generally strives to make it as easy as possible to load models, CORS is something that we cannot fix for you. The server where the model is hosted has to serve the appropriate headers in order for `<model-viewer>` to load that model, otherwise the browser will close the request before we can load anything.

For a more detailed explanation of CORS, please refer to this article: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS

In general, though, you can decide what to do by answering this question:


Do you control the server that is running at `In3dReal.net`?
If yes, configure it to send permissive CORS headers when serving 3D models
If no, you must host the models somewhere that can send permissive CORS headers with the response

**Comment by IvanNov7** [comment]
@cdata 
Thank you! Will try solve that with my host.
Sorry for off-topic, maybe you can recommend some place to host or locate the models that works fine?

**Comment by cdata** [comment]
I mostly just make small demos myself, so I use glitch.com. Glitch sets permissive CORS headers by default. If you used something like an Amazon S3 or Google Cloud storage container, I am guessing that would probably also work fine (or could be configured to work fine).
