### ISSUE TITLE
Find out if the Android Device supports AR before displaying the icon

### ISSUE THREAD

**Issue by charpstar** [google/model-viewer#987]
Currently, the AR icon and custom AR icons show up on all Android Devices regardless of their support for AR. I was wondering if there was a method/CSS or similar to detect if a device supports AR and then hide the AR icon if it's unsupported. 

I'm aware that there's a fallback i.e where the Scene Viewer just shows the 3D viewer and not the AR on these devices but this works sometimes and bugs out the most of the time. 

Is there a solution for this that I'm missing. Thanks for reading

**Comment by cdata** [comment]
@charpstar unfortunately, it's currently impossible for a script running in a browser to know if an Android phone has a specific app installed. Since Android AR is currently achieved using an external app called Scene Viewer, the only way to determine if AR is available is to try to launch the app. To make matters more complicated, the only time we are allowed to try to launch the app is when the user presses the button.

Eventually, WebXR will allow us to launch AR via the web, without relying on a native app. When this happens (and I'm told it will happen soon for Chrome), we will make it possible to hide the button when WebXR-based AR is not available.

**Comment by charpstar** [comment]
Thanks @cdata 

For now, we've found a (not so good) workaround where we sniff the user agent of the browser and then hide the badge if it does not correspond to the model number of an ARCore supported device. 

Unfortunately it's manual work and we have to continuously update the list as more ARCore supported devices are launched. But this seems better than the alternative of having a non responsive button on older devices. 

Hoping for a more seamless connection to Sceneviewer through html

Thanks again

**Comment by cdata** [comment]
Note that even though a phone doesn't have ARCore, it might have Scene Viewer. Scene Viewer has a non-AR 3D turntable mode that works on devices without ARCore. The only technical requirement for a device to have Scene Viewer (that I know of) is that it has the Google Search app installed.

**Comment by charpstar** [comment]
Hmm not sure about that. A few of my lower end Android test phones and also my Nvidia Shield all have the Google Search app and scene viewer does not start up in those. They all seem to simply fullscreen the model viewer model. 

However, when i force installed "Google Play Services for AR" on an unsupported device with an external APK, scene viewer started working. Although it crashes a lot as expected. 

Regarding the issue at hand, the main usecase for our clients is the AR feature so I think our solution is the best workaround for now.

**Comment by cdata** [comment]
Actually, you are right. I forgot that we are using a special version of the intent that will only launch Scene Viewer if ARCore is enabled (because it triggers Scene Viewer via ARCore). However, it is possible (and even likely) that these devices could launch Scene Viewer without AR.
