### ISSUE TITLE
Offsetting the horizontal plane - levitating objects

### ISSUE THREAD

**Issue by klemenvip** [google/model-viewer#998]
Is it possible to offset the horizontal plane which would allow you to place the object above ground to the desirable height? 

Doing this would allow you to place an object on the table and then using a vertical scale (+2m) to raise the object above ground to a desirable height. 

With it you could also fake vertical placement in that the object is attached to the vertical plane or that the object is hanging form the ceiling.

**Comment by cdata** [comment]
This is definitely something we have discussed for WebXR-based AR mode.

Currently it is not available, but we should add a configuration for it 👍 I believe we referred to this concept as an "offset translation," which is defined as a scalar value that offsets the model from the surface it rests upon.

**Comment by elalish** [comment]
This can be achieved with a static animation transform in the glTF, since the bounding box is based on the resting state.

**Comment by vortice3D** [comment]
Hi there, @elalish:

Well, this is a so-called "closed" issue, but I respecfully think that to in reching a specific animación frame in order to implement a traslation offset is not a very clean-code practice, indeed.

Any hope to hace this done the right way?, That is vía transforma, as rotation ans scaling are already done.

BEST regards.

**Comment by elalish** [comment]
Agreed, let's continue the discussion here: https://github.com/google/model-viewer/discussions/4442#discussioncomment-6931386
